### PR TITLE
Efficient plotting when evaluating network

### LINKED ISSUE #910: Failure to evaluate network with plotting on with large training sets
Related to one of the sub-issues in #878, and to #835 , but I think worthy of elevating to its own issue since both of those other issues covered multiple issues, and this one was never solved (just worked around). I've tried to monitor a few things (details below).

**Describe the bug**

During evaluating network with plotting, I get a wx._core.wxAssertionError (the same as mentioned [here](https://github.com/DeepLabCut/DeepLabCut/issues/878#issuecomment-683074629) and at the start of #835 . Some but not all plots are saved, and no other evaluation outputs are returned.

**Desktop (please complete the following information about your system):**
 - OS: Windows 10, 64 GB, 24 GB GPU
 - DeepLabCut Version: 2.2b8 - clean install of conda env 15 Sept.
 - Browser, if applicable [e.g. chrome, safari]

**To Reproduce**
Same with GUI or from command line:
1. Create training dataset with large number of input images, and crop and label True.
2. Train Network
3. Evaluate Network with plotting on

<details><summary>TRACEBACK</summary>
<p>

```python

1219it [05:34,  3.64it/s]
Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\gui\evaluate_network.py", line 340, in evaluate_network
    comparisonbodypart
s=self.bodyparts,
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py", line 583, in evaluate_network
    c_engine=c_engine,
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py", line 343, in evaluate_multianimal_full
    cfg["pcutoff"],
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\utils\visualization.py", line 109, in make_multianimal_labeled_image
    fig, ax = prepare_figure_axes(w, h)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\utils\visualization.py", line 185, in prepare_figure_axes
    frameon=False, figsize=(width * scale / dpi, height * scale / dpi), dpi=dpi
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\pyplot.py", line 545, in figure
    **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1969, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1973, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1103, in __init__
    self.toolbar = self._get_toolbar(self.statusbar)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1131, in _get_toolbar
    toolbar = NavigationToolbar2Wx(self.canvas)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1377, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backend_bases.py", line 2636, in __init__
    self._init_toolbar()
  File "C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\matplotlib\backends\backend_wx.py", line 1413, in _init_toolbar
    self.Realize()
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar  


```

Also, possible relevant proceeding FutureWarnings and RuntimeWarnings. There are MANY of these, I'm assuming related to cropped training images when all points have been cropped out. But maybe not trying to save these would prevent memory issues?
```python
1216it [04:52,  3.84it/s]C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py:266: FutureWarning: Pass-through of possibly RGB images in gray2rgb is deprecated. In version 0.19, input arrays will always be considered grayscale, even if the last dimension has length 3 or 4. To prevent this warning and ensure compatibility with future versions, detect RGB images outside of this function.
  frame = img_as_ubyte(skimage.color.gray2rgb(image))
C:\Users\jacksonbe3\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py:280: RuntimeWarning: All-NaN slice encountered
  distnorm[imageindex] = np.nanmax(lengths)
```
</p></details>

**Expected behavior**
Evaluated images from all images in the training set, and other evaluation outputs

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above!)

**Additional context**
Many labeled images are produced (ca. 1215), but with a large number of labelled images, and "Crop and Label" selected when creating the the dataset, this isn't all of them. Therefore, it acts like a memory leak issue, also suggested by and with a possible strategy for a fix [here](https://stackoverflow.com/a/61920189).

Task Manager shows a gradual ongoing drop in available RAM, with this process eventually taking up about 2.5 GB as the evaluate process continues, so it doesn't seem to be releasing memory after creating each figure. However, when it fails, I still have about 45 GB free, so if it is a memory problem it's a problem with pre-allocation and not total available memory. In fact, that memory isn't released even with the error and the process stopping; it is only released if I start another evaluation process (or close the GUI).

There isn't an error with smaller training sets with crop and label. or the same project without crop and label, or this data set but without plotting, so it doesn't seem to be something fundamental to the version of wxpython, but indeed something about memory handling.

Importantly, with plotting off, evaluation completes and returns everything (other than the images).

### PR DESCRIPTION
**Pull request by jeylau**
Figure is now created only once, and efficiently drawn and erased in the loop.
I tested it over a folder of 3000+ images and this successfully keeps memory use constant.
- [x] multi-animal project
- [x] single-animal project

Fixes #910

### CODE REVIEW

**Comment by AlexEMG** [comment]
On blank install, followed first  https://github.com/DeepLabCut/DeepLabCut/issues/893

**Comment by jeylau** [comment]
@MMathisLab, it should now be functional for single animal projects! 😊

**Comment by MMathisLab** [comment]
to anyone following, still having issues running this on ubuntu; but if you use windows, @backyardbiomech this should be functional for you! (sorry for the delay in updating you!)

**Comment by hummuscience** [comment]
Was using the recent official release with `pip install deeplabcut==2.2b8` but had this issue.

Did a git pull on the repo and `pip install .` The error prevails. I am on Windows using DLC-GPU.

My wx version: 4.0.4

The error persisted with `pip install -U wxPython==4.0.7.post2`

Updating to the most recent wxPython version (4.1.1) resolved the issue.

```
1218it [07:02,  3.40it/s]C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py:260: FutureWarning: Pass-through of possibly RGB images in gray2rgb is deprecated. In version 0.19, input arrays will always be considered grayscale, even if the last dimension has length 3 or 4. To prevent this warning and ensure compatibility with future versions, detect RGB images outside of this function.
  frame = img_as_ubyte(skimage.color.gray2rgb(image))
1219it [07:03,  3.33it/s]C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py:260: FutureWarning: Pass-through of possibly RGB images in gray2rgb is deprecated. In version 0.19, input arrays will always be considered grayscale, even if the last dimension has length 3 or 4. To prevent this warning and ensure compatibility with future versions, detect RGB images outside of this function.
  frame = img_as_ubyte(skimage.color.gray2rgb(image))
1219it [07:03,  2.88it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\gui\evaluate_network.py", line 340, in evaluate_network
    comparisonbodyparts=self.bodyparts,
  File "C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\evaluate.py", line 583, in evaluate_network
    c_engine=c_engine,
  File "C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py", line 337, in evaluate_multianimal_full
    cfg["pcutoff"],
  File "C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\utils\visualization.py", line 109, in make_multianimal_labeled_image
    fig, ax = prepare_figure_axes(w, h)
  File "C:\Users\Administrator\Downloads\repos\DeepLabCut\deeplabcut\utils\visualization.py", line 185, in prepare_figure_axes
    frameon=False, figsize=(width * scale / dpi, height * scale / dpi), dpi=dpi
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\pyplot.py", line 545, in figure
    **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1969, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backend_bases.py", line 3261, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1973, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1103, in __init__
    self.toolbar = self._get_toolbar(self.statusbar)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1131, in _get_toolbar
    toolbar = NavigationToolbar2Wx(self.canvas)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1377, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backend_bases.py", line 2636, in __init__
    self._init_toolbar()
  File "C:\Users\Administrator\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1413, in _init_toolbar
    self.Realize()
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar
```

**Comment by backyardbiomech** [comment]
I did a clean install of 2.1.9 pulled from the `plot_evaluate` branch today, and loaded my project and evaluated via the main GUI. I can confirm memory leak continued to failure with `wxPython==4.0.4`, as indicated in memory use in Windows Task Manager and with the same ultimate error posted by @Cumol above.

Updating the conda env with  `pip install -U wxPython==4.1.1` fixed it!
Task manager confirms constant low memory use. It is still running (about an hour left to make plots for another 2000 images), but I suspect it will complete based on the Task Manager. I'll post if it fails.

**Comment by MMathisLab** [comment]
wow, that's great - only reason we haven't merged this PR is that there is some issue with linux we haven't fully debugged, but really glad to hear 4.1.1 is also working! Although I just tried and I do have issues w/4.1.1 with the labeling tools! 

Maybe when you upgraded wxPython it forced the upgrade? if you run `./reinstall.sh` with 4.0.7.post2 is the memory leak still there?

**Comment by hummuscience** [comment]
@MMathisLab It seems like the labelling tools *do not* work with 4.1.1 (but do work with 4.0.7.post2) while the network evaluation only works with 4.0.7.post2. 

There is probably some build in between where both magically work. For now I am switching between both depending on what I am doing.

**Comment by backyardbiomech** [comment]
Yes, with wxPython 4.1.1 trying to open the label frames GUI leads to the following traceback which is reported elsewhere in this repo as connected to wxPython:

```python
Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\gui\label_frames.py", line 151, in label_frames
    deeplabcut.label_frames(self.config)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 427, in label_frames
    multiple_individuals_labeling_toolbox.show(config)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 1345, in show
    frame = MainFrame(None, config).Show()
  File "C:\Users\jacksonbe3\Miniconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 289, in __init__
    widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2168) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
```

However, changing the problematic line from
```python
widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15) 
```

to

```python
 widgetsizer.Add(self.quit, 1, wx.ALL , 15)
```

fixes the issue (on Windows), and the quit button appears unmoved. The change also fixes the error with the single animal labeling GUI, and single and multi animal refining GUI.

However, the refining tracklets GUI is another story. It appears to open files, play, drag, save, etc. just fine. However, closing the refining tracklets GUI window with the X leads to an hourglass cursor, then crash of the main GUI and python instance with no output to the terminal. The same crash with ipython happens when calling the tracklet GUI from the command line:

```python
In [7]: dlc.refine_tracklets(config, sk, vid)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]

(DLC) C:\Users\jacksonbe3\Documents\repos\DeepLabCut>    
```

FWIW, my env build is here:
<details>

```
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.11.0             pyhd3eb1b0_1
argon2-cffi               20.1.0           py37he774522_1
astor                     0.8.1                    py37_0
async_generator           1.10             py37h28b3542_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bayesian-optimization     1.2.0                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.2.1                      py_0
ca-certificates           2020.12.8            haa95532_0
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.4           py37hcd4344a_0
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0
cudatoolkit               10.0.130                      0
cudnn                     7.6.5                cuda10.0_0
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
decorator                 4.4.2                      py_0
deeplabcut                2.1.9                    pypi_0    pypi
defusedxml                0.6.0                      py_0
easydict                  1.9                      pypi_0    pypi
entrypoints               0.3                      py37_0
filterpy                  1.4.5                    pypi_0    pypi
gast                      0.4.0                      py_0
geos                      3.8.0                h33f27b4_0
grpcio                    1.31.0           py37he7da953_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2021.1.2                 pypi_0    pypi
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.19.0           py37hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.5.1                      py_1
jedi                      0.17.0                   py37_0
jinja2                    2.11.2                     py_0
joblib                    1.0.0                    pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.7                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.7.0            py37haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.3.1                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.13.0.1             h200bbdf_0
libsodium                 1.0.18               h62dcd97_0
llvmlite                  0.34.0                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.3            py37haa95532_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.1.3                    pypi_0    pypi
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.2                      256
mkl-service               2.3.0            py37h196d8e1_0
mkl_fft                   1.2.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
mock                      4.0.3              pyhd3eb1b0_0
moviepy                   1.0.1                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
msys2-conda-epoch         20160418                      1
nb_conda                  2.2.1                    py37_0
nb_conda_kernels          2.3.1            py37haa95532_0
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nest-asyncio              1.4.3              pyhd3eb1b0_0
networkx                  2.5                      pypi_0    pypi
notebook                  6.1.6            py37haa95532_0
numba                     0.51.1                   pypi_0    pypi
numexpr                   2.7.2                    pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
opencv-python             4.4.0.46                 pypi_0    pypi
opencv-python-headless    4.4.0.46                 pypi_0    pypi
openssl                   1.1.1i               h2bbff1b_0
packaging                 20.8               pyhd3eb1b0_0
pandas                    1.1.5                    pypi_0    pypi
pandoc                    2.11                 h9490d1a_0
pandocfilters             1.4.3            py37haa95532_1
parso                     0.8.1              pyhd3eb1b0_0
patsy                     0.5.1                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3.3           py37haa95532_0
proglog                   0.1.9                    pypi_0    pypi
prometheus_client         0.9.0              pyhd3eb1b0_0
prompt-toolkit            3.0.8                      py_0
prompt_toolkit            3.0.8                         0
protobuf                  3.13.0.1         py37ha925a31_1
psutil                    5.8.0                    pypi_0    pypi
pycparser                 2.20                       py_2
pygments                  2.7.3              pyhd3eb1b0_0
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.17.3           py37he774522_0
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
pytz                      2020.5                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0           py37hd77b12b_1
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.7.7                      py_0
qtpy                      1.9.0                      py_0
requests                  2.25.1                   pypi_0    pypi
ruamel-yaml               0.16.12                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.24.0                   pypi_0    pypi
scipy                     1.5.2            py37h9439919_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                51.0.0           py37haa95532_2
shapely                   1.7.1            py37h210f175_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0           py37haa95532_0
sqlite                    3.33.0               h2a8f88b_0
statsmodels               0.12.1                   pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               1.13.1           py37h33f27b4_0
tensorflow                1.13.1          gpu_py37h83e5d6a_0
tensorflow-base           1.13.1          gpu_py37h871c8ca_0
tensorflow-estimator      1.13.0                     py_0
tensorflow-gpu            1.13.1               h0d30ee6_0
tensorpack                0.9.8                    pypi_0    pypi
termcolor                 1.1.0                    py37_1
terminado                 0.9.1                    py37_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2020.12.8                pypi_0    pypi
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.55.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wxpython                  4.1.1                    pypi_0    pypi
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
```
</details>

**Comment by MMathisLab** [comment]
yeah, indeed that seems to be a good quick fix, but at least on my mac, although it works (labeling GUIs), I get the following traceback:

```python
wx._core.wxAssertionError: C++ assertion ""w > 0 && h > 0"" failed at /Users/robind/projects/bb2/dist-osx-py37/build/ext/wxWidgets/src/osx/core/bitmap.cpp(1009) in Create(): invalid bitmap size
```

We are pretty close to changing out the GUIs for napari actually so I'm less inclined to figure the sources now for wxPython, but of course want it to work for you -- you'd be a great beta tester for the napari GUI 👯

**Comment by backyardbiomech** [comment]
I'd be happy to test. I have been thinking about trying to rewrite the Argus clicker interface with Napari (currently pyglet). 
I also have deeplabcut running on macOS 10.15.7 and 11.1 (with an M1 chip), and Windows 10.

**Comment by MMathisLab** [comment]
small, update, https://github.com/DeepLabCut/DeepLabCut/pull/1155 is working with 4.1.1 wxpython currently (at least the labeling GUI), in case one wants to test this!

**Comment by jeylau** [comment]
> small, update, #1155 is working with 4.1.1 wxpython currently (at least the labeling GUI), in case one wants to test this!

I too have all GUIs now working with 4.1.1 (on macOS Big Sur :)

**Comment by MMathisLab** [comment]
status on this @AlexEMG ?

**Review by MMathisLab — APPROVED** [review]

**Pull request closed without merging**
