### PR TITLE
Rename test_modelzoo.py

### PR DESCRIPTION
**Pull request by jeylau**
Note that the test of the download of all individual model zoo models is skipped by default (but can be run locally occasionally).

- [ ] mark download test with attribute

### CODE REVIEW

**Comment by MMathisLab** [comment]
why don't we make it run tag-based? ie. like this: https://github.com/AdaptiveMotorControlLab/CEBRA/blob/a21ba0ec17a8c7cc67fc24187f119a52c4132cd0/tests/test_datasets.py#L142 in https://github.com/AdaptiveMotorControlLab/CEBRA/pull/52

**Comment by jeylau** [comment]
Yes, good idea! I'd go for `@parametrize.mark.slow` then, which can easily be run from the CLI. Let me move this to WIP.

**Comment by MMathisLab** [comment]
maybe a small bump here so we can have this in before SA PRs are merged

**Comment by jeylau** [comment]
I'd close the PR and delete the test_modelzoo file, since all model downloads are now systematically tested at `dlclibrary` https://github.com/DeepLabCut/DLClibrary/blob/main/tests/test_modeldownload.py.

**Pull request closed without merging**
