### PR TITLE
Fixed OOM error and added Cupy support for tracklets

### PR DESCRIPTION
**Pull request by PolarBean**
Fixed the OOM error discussed over here https://github.com/DeepLabCut/DeepLabCut/issues/778
and added cupy support to make the analysis of longer videos feasible.

### CODE REVIEW

**Comment by PolarBean** [comment]
I added another commit to my branch but Im not sure if this auto updates this pull request

**Comment by PolarBean** [comment]
I think we could make this extremely fast if we forego the initialisation of empty arrays entirely, this should be possible in the initial creation loop (line198) as we no longer store that array anyway. Not sure how to go about it in the autofill loop though (line 228)

**Comment by jeylau** [comment]
Hey @PolarBean, thanks a lot for taking a shot at it! What you mentioned above sounds like promising avenues; I'll try to come up with a leaner version of the current code ASAP and get back to you. 😃

**Comment by PolarBean** [comment]
Great! yeah my codes a bit rough but Im sure theres a cleaner implementation :P

**Comment by jeylau** [comment]
> Great! yeah my codes a bit rough but Im sure theres a cleaner implementation :P

Don't get me wrong, I meant a leaner version of my original implementation 😄

**Comment by jeylau** [comment]
@PolarBean, I've added you as a co-author to that commit 75fba83a8642fd0c72fff8d2bcd7c0d54905214d. Your profiling of the code greatly helped me getting rid of the large arrays, and we now make better use of advanced indexing 😃. I have tried it on an artificial 700-mb pickle, and it loads tracklets at 2500 fps. Let me know how it does on your data!

**Comment by PolarBean** [comment]
Wow Im really impressed you achieved this without my gpu trickery. Awesome job, thanks for making me co-author :) ill run this on some big data files tomorrow morning and let you know how I go. Really cool 😊😊😊

**Pull request closed without merging**
