### PR TITLE
Add dlclibrary for model download from zoo

### LINKED ISSUE #2086: Model zoo google colab: full_human package huggingface URL has been change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Model zoo google colab huggingface link(url) to full_human pre-trained model has been changed. This results in an error.

### Operating System

operating system Google Colab

### DeepLabCut version

dlc version 2,23

### DeepLabCut mode

single animal

### Device type

gpu google colab

### Steps To Reproduce

Run the DeepLabCut Model Zoo as default and select the full_human pre-trained model. It will give you the below output. However, when I checked it for the full_cat, it worked perfectly. The huggingface link(URL) for the full_human package needs to be modified.
Current url: 
https://huggingface.co/mwmathis/DeepLabCutModelZoo-DLC_human_fullbody_resnet_101/resolve/main/DLC_human_fullbody_resnet_101.tar.gz

New url: https://huggingface.co/mwmathis/DeepLabCutModelZoo-DLC_human_fullbody_resnet_101/blob/main/DLC_human_dancing_resnet_101_iteration-0_shuffle-1.tar.gz

### Relevant log output

```shell
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status(response, endpoint_name)
    238     try:
--> 239         response.raise_for_status()
    240     except HTTPError as e:

8 frames
/usr/local/lib/python3.8/dist-packages/requests/models.py in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/mwmathis/DeepLabCutModelZoo-DLC_human_fullbody_resnet_101/resolve/main/DLC_human_fullbody_resnet_101.tar.gz

The above exception was the direct cause of the following exception:

EntryNotFoundError                        Traceback (most recent call last)
<ipython-input-9-651e5f42c530> in <module>
----> 1 config_path, train_config_path = deeplabcut.create_pretrained_project(
      2     project_name,
      3     your_name,
      4     [video_path],
      5     videotype=videotype,

/usr/local/lib/python3.8/dist-packages/deeplabcut/create_project/modelzoo.py in create_pretrained_project(project, experimenter, videos, model, working_directory, copy_videos, videotype, analyzevideo, filtered, createlabeledvideo, trainFraction)
    277         # AM: Rowland server down...
    278         #auxfun_models.download_model(model, train_dir)
--> 279         auxfun_models.download_hugginface_model(model, train_dir)
    280 
    281 

/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_models.py in download_hugginface_model(modelname, target_dir)
    182         repo_id,targzfn=url[0]+'/'+url[1],str(url[-1])
    183 
--> 184         hf_hub_download(repo_id,targzfn,cache_dir = str(target_dir))
    185         #creates a new subfolder as indicated below, unzipping from there and deleting this folder
    186 

/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py in _inner_fn(*args, **kwargs)
    122             )
    123 
--> 124         return fn(*args, **kwargs)
    125 
    126     return _inner_fn  # type: ignore

/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py in hf_hub_download(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, user_agent, force_download, force_filename, proxies, etag_timeout, resume_download, token, local_files_only, legacy_cache_layout)
   1065         try:
   1066             try:
-> 1067                 metadata = get_hf_file_metadata(
   1068                     url=url,
   1069                     token=token,

/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py in _inner_fn(*args, **kwargs)
    122             )
    123 
--> 124         return fn(*args, **kwargs)
    125 
    126     return _inner_fn  # type: ignore

/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py in get_hf_file_metadata(url, token, proxies, timeout)
   1374         timeout=timeout,
   1375     )
-> 1376     hf_raise_for_status(r)
   1377 
   1378     # Return

/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status(response, endpoint_name)
    255                 + f"Entry Not Found for url: {response.url}."
    256             )
--> 257             raise EntryNotFoundError(message, response) from e
    258 
    259         elif error_code == "RepoNotFound" or response.status_code == 401:

EntryNotFoundError: 404 Client Error. (Request ID: Root=1-63970504-0a3b8fce60cd84e628332e1c)

Entry Not Found for url: https://huggingface.co/mwmathis/DeepLabCutModelZoo-DLC_human_fullbody_resnet_101/resolve/main/DLC_human_fullbody_resnet_101.tar.gz.
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jeylau**
Fixes #2086

### CODE REVIEW

**Review by AlexEMG — CHANGES_REQUESTED** [review]
the /tools files should stay. Let's also add a unit-test for downloading model zoo weights to DLC (so we catch problems with DLClib here)?

**Comment by AlexEMG** [comment]
also let's add dlclib to setup.py?

**Comment by jeylau** [comment]
> the /tools files should stay. Let's also add a unit-test for downloading model zoo weights to DLC (so we catch problems with DLClib here)?

why? it's part of dlclib too

**Comment by AlexEMG** [comment]
Right, good to use CLI at DLClib, but I think testing it here too, will make sure that we catch it (as I assume we and others look more on DLC's CLI).

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
ready to merge @jeylau ? @yeshaokai ?

**Comment by yeshaokai** [comment]
I haven't tested all cases. It works for my use cases.

**Review by AlexEMG — APPROVED** [review]

**Pull request merged**
