### PR TITLE
Speed up maDLC workflow when there is only one animal

### PR DESCRIPTION
**Pull request by jeylau**
Bypass assembly and tracking if only one individual is defined. Since there will be only one resulting tracklet, stitching is instantaneous so it doesn't need an update.

### CODE REVIEW

**Review by AlexEMG — APPROVED** [review]

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
@jeylau can you add in the docs somewhere so it's clear for single animal in multi-mode users know how this works? then approved fully 👯

**Comment by jeylau** [comment]
@MMathisLab, nothing changes for the users; it's done under the hood (in pretty much the same way we treat uniquebodyparts) ☺️ Or is that precisely what you want me to document? 😄

**Comment by backyardbiomech** [comment]
Since this would apply to my current project of focus...

I would still run `convert_detections2tracklets` and `stitch_tracklets` separately, but it would be faster?

**Comment by jeylau** [comment]
@backyardbiomech, yes! Instead of assembling keypoints, we keep the ones with highest confidence (as in single animal projects), and there is no "tracking": we'll simply form a single track containing all detections.

**Comment by MMathisLab** [comment]
Hey @jeylau actually though, I would be most excited if someone can just run analze_videos and if they pass something like `num_of_animals=1` then it auto runs  `convert_detections2tracklets` and `stitch_tracklets`

**Comment by jeylau** [comment]
@MMathisLab, I'll PR this separately one. We can bundle all the maDLC steps into `analyze_videos` (with the most relevant arguments) to have a behavior close to that of single animal projects. That's the idea, right?

**Comment by MMathisLab** [comment]
yep! But I think the true single step for maDLC is indeed another PR, but for this I think a simple `#animal=True/1` flag would be good; also for real-time DLC things in the future

**Comment by jeylau** [comment]
Got you! This can be edited in the test/inference_cfg.yaml with `topktoretain` (which is otherwise set to the # of animals in the main config.yaml by default)

**Comment by MMathisLab** [comment]
Yep! exactly; I was thinking that if num_animals=1, that would write into the `inference_cfg.yaml`  `topktoretain` =1, so then your code would then it auto runs `convert_detections2tracklets` and `stitch_tracklets` -- no reason to not have this all together; i.e., why should I even need to run them at all.

**Pull request merged**
