### PR TITLE
Fix windows video selection for extraction in the GUI

### PR DESCRIPTION
**Pull request by KonradDanielewski**
`QtWidgets.QFileDialog.getOpenFileNames` outputs unix formated paths which on Windows leads to wrong reading and uninformative output "Video file corrupted" which isn't true. This fix normalizes the path according to `os`

### CODE REVIEW

**Review by n-poulsen — APPROVED** [review]

**Comment by MMathisLab** [comment]
@n-poulsen see you approved, but all tests are failing?

**Comment by n-poulsen** [comment]
They're failing due to the issue with `scipy-1.11.1` (which is fixed as we pinned `scipy`). I'll merge the changes made to main and re-run the tests.

**Review by jeylau — APPROVED** [review]

**Comment by skd217** [comment]
Hi there,
Based on the earlier conversations, I checked the component.py file and found correct. But I am still facing the problem with extracting frames from videos. Even though the pop-up appears instantly stating frames are extracted successfully, but the process did not run actually. On the prompt, it did not show any run command:
>python -m deeplabcut
2024-08-19 18:50:34.261950: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-08-19 18:50:34.262322: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading DLC 2.3.10...
Starting GUI...

I am working on Windows 11, DLC 2.3.10, single animal, CPU.

Any help in this regard is greatly appreciated?

**Comment by n-poulsen** [comment]
Hi @skd217 - have you been able to extract frames for any project, or does it always fail?

**Comment by skd217** [comment]
Hi @n-poulsen,
Unfortunately, it’s still not working. I also attempted converting the videos (originally in .mov format, recorded on an iPhone) into different formats (.mp4, .avi, etc.), but that didn’t resolve the issue either.

**Comment by n-poulsen** [comment]
Are you working with the GUI or with code? If you're working with the DeepLabCut GUI, could I ask you to run the commands to extract frames using python code, and let me know if any errors occur?

You can extract frames with code (as mentioned [in our docs](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#c-data-selection-extract-frames)) by running `ipython` from your Anaconda prompt, and then running:

```python
import deeplabcut

config_path = r"C:\path\to\DLC\project\config.yaml"
deeplabcut.extract_frames(config_path, mode="automatic", userfeedback=False)
```

**Comment by skd217** [comment]
Hi @n-poulsen Finally, I am able to extract the frames using ipython as suggested. Initially, I was struggling with GUI. 
Thank you very much !!

**Pull request merged**
