### PR TITLE
Experiment : API documentation in Jupyter Book docs

### PR DESCRIPTION
**Pull request by rahulporuri**
At the moment, the API documentation for the user-facing functions in `deeplabcut` are hosted on the [docstrings wiki page](https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS). This isn't ideal as every time the docstring of a function is updated, the wiki needs to be updated, which external contributions don't often have edit access to.

This is experimental PR demonstrates including API documentation in the Jupyter Book documentation directly. The necessary changes are:

- add a new `docs/api/deeplabcut.create_project.new.rst` file, which automatically documents the function `create_new_project`. This file was created and populated manually
- include this file in `docs/standardDeepLabCut_UserGuide.md` in the "(A) Create a New Project" section
- install the `deeplabcut` package into the environment before building the jupyter book docs

With these changes, the API documentation for the `create_new_project` function can be included in the "(A) Create a New Project" section of the "DeepLabCut user guide".

image

Additionally, this PR introduces a few more changes

- formats and updates the docstring for `create_new_project` according to the [numpydoc style guide](https://numpydoc.readthedocs.io/en/latest/format.html)
- make `numpydoc` an optional documentation dependency of `deeplabcut`
- include `numpydoc` as an extra sphinx extension in the jupyter book config file
- update the github workflow to install the docs dependencies when installing `deeplabcut`

### CODE REVIEW

**Comment by rahulporuri** [comment]
@MMathisLab and @AlexEMG - can you please take a look at this PR at your convenience?

If this approach looks like an improvement to you, I plan on opening PRs to bring all of the docstrings listed in the wiki page https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS into the jupyter book docs.

**Comment by MMathisLab** [comment]
this is super userful, thank you @rahulporuri

**Review by AlexEMG — APPROVED** [review]

**Comment by AlexEMG** [comment]
Thanks @rahulporuri -- that is great and I like the style!

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
Hey @rahulporuri thanks again! for keeping the docs not too bloated looking, for the next ones could I ask we add this "click to open" option? see https://github.com/DeepLabCut/DeepLabCut/commit/4e03b4b97089cdd54f2edc51ec4818996c60329c

**Pull request merged**
