### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by roaldarbol**
Hi guys! Hope this finds you well.
I've started a bunch tracking projects for myself and my colleagues recently, and especially the installation (on Windows, the usual CUDA/TF stuff) is a major stumbling point. So I thought I might as well update the documentation as I go along to. :-)

DeepLabCut has grown into an amazing ecosystem of tools, and I think the documentation has sort of grown equally to be a lot of smaller parts - and understandably so! But I think it would greatly improve the UX to streamline the documentation - give it an overhaul, and keep related information closer together. 

For now, if you want to get an idea how I could imagine it looking, have a look at the `Install with conda` page in particular - I'm very happy to adapt if you have other ideas/visions of your own. But otherwise, I'm happy to just labour on over the coming months (have a tight deadline coming up in 3 weeks, so can spend more time on it afterwards)

Additionally, I've changed the `_config.yml` according to the default Jupyter Book file to expose all the options. Of course, I've kept the settings the same, it's more to make it easier for outsiders to contribute to the docs. 

For now, leave the pull request open now matter what as I'm nowhere done with it. 

PS From the default DLC installation I've needed to add some dependencies to the `conda` repo to be able to build the docs (didn't have e.g. `jupyter-book`). Do you have a special config file for development that contains these? Or do you have a list?

Cheers,
Mikkel

### CODE REVIEW

**Comment by MMathisLab** [comment]
hi @roaldarbol thanks for the contribution! A lot of changes, so it will take a while for me to work through it, but I agree our Windows in particular should be updated (none of us use windows regularly, as it's really a pain!). 

I will note that we are in the middle of a big road-map listed overhaul of dropping tensorflow as well, so some bits about install will change there too.

**Comment by roaldarbol** [comment]
Hi @MMathisLab, sorry about the delayed response, suddenly had a lot of prep for a workshop. And no worries if you don't have time to review the PR currently, I get there will always be crunch periods, and my PR ended up being a bit messy, apologies! I haven't done too many PR requests before, so didn't have the review process in mind when I was typing away. :-)

The current bigger picture changes are as follows:
- Landing page with sparse information
- Unify installation docs in a single page
- Expose all parameters in `_config.yaml` to make future changes easier

In terms of how to proceed from here on: Would you rather that we have a chat about what you would like from the docs, or should I churn on?
I am actively trying not to loose any information in the process, but for now they might change places and end up in different/new documents (that may or may not be included in the built site). I can revert to just having those changes and then make subsequent changes in new PRs if that'll be easier. Otherwise, I was thinking of running my changes in a separate version in my fork, so there would be an online version you could gauge the changes... maybe we can make a `new_docs` branch, and I can make PRs to that branch until further notice?

I am more than happy to help out testing stuff on Windows for you, especially from a UX perspective if that would be helpful! I usually run MacOS as my main, Windows on institutional devices (with better GPUs) and occasionally Raspberry Pi, though I hope no one's crazy(brave?) enough to try it there. ;-)

PS: Also really pleased to hear you'll be migrating away from TF, it just seems to be causing issues in the various libraries I've encountered it as a user.

**Comment by MMathisLab** [comment]
thanks again for this! We are going to overall the docs a bit, but the soon-to-be-out PyTorch version is simplifying things; we make some adjustments here based on your feedback: https://github.com/DeepLabCut/DeepLabCut/pull/2495, but this means we will close this PR for now!

**Comment by roaldarbol** [comment]
No worries, glad that it helped! I'd also be happy to provide some feedback on the new docs PR if you'd like an outsider's perspective. 😊

**Comment by MMathisLab** [comment]
Absolutely 🥰🙏🏼

**Pull request closed without merging**
