### PR TITLE
Define crop coordinates in GUI when analyzing videos.

### PR DESCRIPTION
**Pull request by jeylau**
The GUI was passing True/False rather than a list of coordinates to 'cropping' in analyze_videos.
#560 is now fixed, and the documentation has been slightly improved to avoid confusion ('cropping' has also been renamed to 'crop', consistent with all other functions expecting a list rather than a boolean).

### CODE REVIEW

**Comment by MMathisLab** [comment]
The idea with cropping = True was that it should read the values from the config.yaml file though, but now I have to enter this again into the GUI? @jeylau 

and cropping and crop were separated as they have different names in config.yaml, albeit this is perhaps confusing.

**Comment by MMathisLab** [comment]
also this means it's not backwards compatable with older projects, as cropping is used in the config.yaml
```

# Cropping Parameters (for analysis and outlier frame detection)
cropping: false
#if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624
```

**Review by MMathisLab — CHANGES_REQUESTED** [review]
crop should be reverted to cropping, and the default behavior is that if cropping=true then the config.yaml file is read and those coordinates are used.

**Comment by jeylau** [comment]
I have removed the 'cropping' panel in the GUI, so we now only rely on whether it is True/False in the config.yaml. I kept the argument as 'crop' in `analyze_videos()` to indicate we expect coordinates (which is also consistent with 'crop' in video_sets) vs 'cropping' (which implies a boolean).

**Comment by MMathisLab** [comment]
PR good for me now! Thanks @jeylau - @AlexEMG if you're fine, please merge.

**Comment by MMathisLab** [comment]
@alexemg please check and merge.

**Comment by AlexEMG** [comment]
Now it's great!

**Pull request merged**
