### PR TITLE
Set confidence to 0 when instantiating Assembly

### LINKED ISSUE #1650: Non-tracked NaN points in maDLC saved with likelihood of 1.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Single animal tracking in maDLC. 

If (part of) the animal starts offscreen, or ends up offscreen, the model, appropriately, cannot create tracks for invisible bodyparts for those frames. The saved coordinates are `nan, nan`. However, the saved likelihood is `1.00000`. 

Other than just being inaccurate, this creates problems in two realms:
1. Applying splines or other filtering regimes post-DLC where weights are based on likelihood thresholds.
2. Importing data to other workflows, especially 3d reconstruction in Anipose (my case), which uses a simple likelihood threshold for including data in calculations. Anipose will triangulate a point in a frame based on the lowest likelihood among the cameras. One camera with nans and 1.0 and another camera with points and 0.99 likelihood leads to problematic 3d reconstructions.

Simply setting the default likelihood to 0.0, or setting to 0 the likelihood for any rows of nans per bodypart, would fix it.

I have not checked to see if this is true in single animal DLC (it shouldn't be though since the nans will only show, I believe, when tracklets can't be formed or stitched for certain frames), or with more than 1 animal in maDLC.

### Operating System

Windows 10

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jeylau**
Default confidence is set to 0 unless overwritten when adding joints/links to the assembly.

Fixes #1650

### CODE REVIEW

**Review by backyardbiomech — APPROVED** [review]
Tested and that fixes it.  Thanks for the quick work. 
I'm wondering, though, what is more appropriate. A likelihood of `nan`, or `0`.

At least in [anipose](https://github.com/lambdaloop/anipose/blob/f4c229b6341f5b3b15e710e18a39f3c8573f9eab/anipose/triangulate.py#L236), `0` might be better because of the way the score for the triangulated point is calculated:

```python
scores_3d = np.min(all_scores, axis=0)
```
Though I think the handling of missing points in anipose needs to be improved beyond this line. 

But I'm also wondering about things like extracting outliers based on "uncertain" when checking for likelihoods **less than** some threshold. Where and how else is likelihood used, and would `0` or `nan` be better in those workflows?

**Comment by AlexEMG** [comment]
Likelihood 0, seems like a reasonable convention that doesn't break any downstream computations.

**Comment by jeylau** [comment]
It mostly depends on whether we want a frame with a missing detection to be caught as outlier with the "uncertain" method.  I'm not certain this is desirable (e.g., when an animal hides), as we'd end up flagging frames for which no user intervention is truly needed. Thoughts?

**Comment by backyardbiomech** [comment]
This isn't an easy problem. I agree that not wanting to flag as uncertain a hiding animal is good, and in some maDLC projects animals may regularly leave the field of view. But at earlier stages of training a model more subtle losses of tracklet building (e.g. animals or limbs too close to each other) can also lead to nans, and those should be flagged. 

What if it's set to 0, but when extracting outliers there's an option to ignore (or set to nan) all zero values (e.g. <0.0001) using the `uncertain` method? That way, with no intervention, threshold-dependent downstream workflows should work, but the user has the option to ignore hiding animals when refining a model.

**Comment by AlexEMG** [comment]
The outlier extraction methods should be updated anyway, to e.g. distinguish an animal disappearing for a while or some jittery predictions (either of which can be likelihood = 0). So I'd say, let's set it to zero and at some point put better extraction methods in?

**Comment by MMathisLab** [comment]
agreel fine to set to 0 for now; requested change needed.

**Review by MMathisLab — CHANGES_REQUESTED** [review]
nan --> 0

**Review by AlexEMG — APPROVED** [review]

**Comment by jeylau** [comment]
Fixed (and edited PR name)!

**Review by AlexEMG — APPROVED** [review]

**Review by MMathisLab — APPROVED** [review]

**Pull request merged**
