### PR TITLE
Better assess frame extraction failure

### PR DESCRIPTION
**Pull request by AlexEMG**
related to: https://github.com/AlexEMG/DeepLabCut/issues/639

### CODE REVIEW

**Comment by MMathisLab** [comment]
Following from the conversation on #639 we should at least through a warning at create_new_project that the video is not correct. 
```
deeplabcut.create_new_project('test4', 'mwm', ['/home/fakenews/video.mp4'])
Created "/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/videos"
Created "/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/labeled-data"
Created "/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/training-datasets"
Created "/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/dlc-models"
Creating the symbolic link of the video
Generated "/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/config.yaml"

A new project with name test4-mwm-2020-03-31 is created at /Users/mwmathis/Documents/DeepLabCut and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
'/Users/mwmathis/Documents/DeepLabCut/test4-mwm-2020-03-31/config.yaml'
```
On this PR this still allows for fake videos to populate the project, but blank in the config.yaml:

``video_sets: {}``

```
(DLC-CPU) mwmathis@Mackenzies-MacBook-Pro DeepLabCut % git status
On branch improved_print
Your branch is up to date with 'origin/improved_print'.
```

although it does not work to extract frames, which is great ;) 

```
deeplabcut.extract_frames(cfp)
Config file read successfully.
Frame extraction failed. Video files must be corrupted.
```

**Comment by jeylau** [comment]
Aw I got you! So let's remove the video files that could not be opened, right?

**Comment by AlexEMG** [comment]
Perhaps more extreme, if **no** video can be added to the `video_sets` dictionary, then the project should not be created and an appropriate error should be displayed?

**Comment by jeylau** [comment]
I thought about it too, and I felt that leaving the project root is fine since the user have the option to add valid videos later on through `add_new_videos.` We could print a statement indicating that no valid videos were found, and that they will have to use the function above though. What do you think?

**Comment by AlexEMG** [comment]
Let's don't create the project at all. So let's just check the dimensions at the very beginning.

**Comment by MMathisLab** [comment]
(we should also include "add new videos" to the main GUI.)

**Comment by MMathisLab** [comment]
fixed the non-functional GUI part; b1de175

**Review by AlexEMG — COMMENTED** [review]
Let's update create project s.t. only if at least one video is loaded correctly (according to dimensions) it creates the files

**Review by jeylau — APPROVED** [review]

**Comment by jeylau** [comment]
That should now work smoothly!

**Review by AlexEMG — COMMENTED** [review]
Great!

**Review by MMathisLab — APPROVED** [review]

**Review by MMathisLab — APPROVED** [review]

**Pull request merged**
