### PR TITLE
upper bound to matplotlib version

### PR DESCRIPTION
**Pull request by KonradDanielewski**
With 3.7.1 switching ID in tracklet refinement GUI doesn't work (at least on Windows)

### CODE REVIEW

**Comment by jeylau** [comment]
Hey @KonradDanielewski, are you getting an error traceback? It seems to work fine on macOS.

**Comment by KonradDanielewski** [comment]
Hi @jeylau . Sorry, sure. It leads to:
```python
Traceback (most recent call last):
  File "C:\Anaconda\anaconda3\envs\dlc_newgui\lib\site-packages\matplotlib\cbook\__init__.py", line 304, in process
    func(*args, **kwargs)
  File "C:\Anaconda\anaconda3\envs\dlc_newgui\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 683, in on_pick
    self.ax_slider.lines.clear()
AttributeError: 'ArtistList' object has no attribute 'clear'
```

**Comment by MMathisLab** [comment]
@jeylau thoughts?

**Comment by jeylau** [comment]
We can close this one; it's fixed with #2216 😊

**Comment by KonradDanielewski** [comment]
Yep, #2216 fixes it

**Pull request closed without merging**
