### PR TITLE
Epipolar lines and related changes

### PR DESCRIPTION
**Pull request by daltondm**
The purpose of this pull request is to add optional epipolar lines to images in the labeling toolbox. This can improve accuracy of the labels in each of the camera images. I also made changes to related code to make this process easier, as well as UseOverviewGuide.md and the DOCSTRINGS in each relevant file.

The updated code was tested on Ubuntu 18.04.

The multianimal testscript seemed to fail somewhere in the training or evaluating phase, but I don't believe this is due to any of my changes. My changes don't extend past the labeling phase and don't change how the labels are saved, and I have successfully used my modifications to take a project past the training and evaluation steps.

Please let me know if you have any questions or need more information.

[Description_of_changes.txt](https://github.com/DeepLabCut/DeepLabCut/files/5017446/Description_of_changes.txt)
epipolar_lines_example_image
[testscript_3d_output.txt](https://github.com/DeepLabCut/DeepLabCut/files/5017447/testscript_3d_output.txt)
[testscript_multianimal_output.txt](https://github.com/DeepLabCut/DeepLabCut/files/5017448/testscript_multianimal_output.txt)
[testscript_output.txt](https://github.com/DeepLabCut/DeepLabCut/files/5017449/testscript_output.txt)

### CODE REVIEW

**Comment by daltondm** [comment]
This modification could be assigned to any of the three reviewers. I have not spoken about the changes to anyone prior to this pull request. If there is a more formal way to assign a reviewer, I didn't see it when submitting (this is my first time contributing to source code). Let me know if you need me to change anything!

**Comment by AlexEMG** [comment]
Thanks for this contribution, that looks very useful! We'll test it and give you feedback.

**Comment by jeylau** [comment]
Hi @daltondm, I am hopeful that you will get my review this weekend. Sorry for the delay 😕.

**Comment by MMathisLab** [comment]
@jeylau could you merge the conflicts, and we can test this out asap; sorry @daltondm for the delay, but we are really keen on accepting it! It's a great idea.

**Comment by daltondm** [comment]
Sounds good, thanks for the update! Don't worry about the delay, I see you have quite a few pull requests to work through.

**Comment by daltondm** [comment]
Hi @jeylau, just following up on this.  No big rush, just want to make sure these modifications don't get forgotten. Thank you!

**Comment by MMathisLab** [comment]
Hey @daltondm sorry for my delay' testing this now. I tested through the paired frame extraction (minor edits and doc updates pushed), but the labeling might need some care; i.e. I think I'd hitting an issue with the `retrieveData_and_computeEpLines` as my cameras are not named `camera-1 `and `camera-2` but rather camera names can be arbitrary, i.e. in my 3d config:
```python
camera_names:
- aa
- b2
```
so I need to look into this a bit more, just wanted to let you know there is movement :D  (or if you have time):

```python
>>> deeplabcut.label_frames(config_path, config3d=config_path3d)
Traceback (most recent call last):
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 774, in browseDir
    self.img, img_name, self.iter, self.index, self.bodyparts, self.colormap
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 184, in drawplot
    epLines, sourcePts, offsets = self.retrieveData_and_computeEpLines(img, itr)
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 81, in retrieveData_and_computeEpLines
    sourceCamIdx = int(re.findall("[0-9]{1,3}", sourceCam)[0]) - 1
IndexError: list index out of range
```

EDIT:

this fixes ^^
```python
sourceCamIdx = np.where(np.array(cams) == sourceCam)[0][0]
labelCamIdx = np.where(np.array(cams) == labelCam)[0][0]
```

**Comment by MMathisLab** [comment]
Hey @daltondm I've decided to not include the 3d parts in the main GUI, since no other 3D parts are in it for now; if users want to use your nice feature, they can use the terminal. We are currently in the process of changing GUIs anyhow, so in the future this can be easier to roll back in. I hope you don't mind.

**Review by MMathisLab — APPROVED** [review]
please merge conflicts, and then it can be approved.

**Comment by MMathisLab** [comment]
I am working on this, but had some issues, so PR #1169 aids in this; I couldn't seem to find another way

**Comment by daltondm** [comment]
Hi @MMathisLab, thanks for testing it all out! Leaving te 3d options out of the GUI for now sounds like a good plan.

**Pull request merged**
