### PR TITLE
Better SkeletonBuilder

### PR DESCRIPTION
**Pull request by jeylau**
Skeleton is built from the config if existent (rather than from scratch systematically).
The necessity of having a fully labeled animal has been relaxed so that the Builder will always show up?

### CODE REVIEW

**Comment by MMathisLab** [comment]
If my config.yaml is:

```
individuals:
- individual1
- individual2
- individual3
uniquebodyparts:
- ice1
- ice2
- ice3
multianimalbodyparts:
- bodypart1
- bodypart2
skeleton:
bodyparts: MULTI!
```
I label frames, and then run build skeleton:

```
Traceback (most recent call last):
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/gui/label_frames.py", line 139, in build_skeleton
    skeleton.SkeletonBuilder(self.config)
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/utils/skeleton.py", line 58, in __init__
    for bone in self.cfg['skeleton']:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/gui/label_frames.py", line 139, in build_skeleton
    skeleton.SkeletonBuilder(self.config)
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/utils/skeleton.py", line 58, in __init__
    for bone in self.cfg['skeleton']:
TypeError: 'NoneType' object is not iterableTraceback (most recent call last):
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/gui/label_frames.py", line 139, in build_skeleton
    skeleton.SkeletonBuilder(self.config)
  File "/Users/mwmathis/Documents/DeepLabCut/deeplabcut/utils/skeleton.py", line 58, in __init__
    for bone in self.cfg['skeleton']:
TypeError: 'NoneType' object is not iterable
```

**Comment by MMathisLab** [comment]
I must connect the skeleton first in the config.yaml, which is not the ideal behavior. 

Screen Shot 2020-05-30 at 3 44 37 PM

**Comment by jeylau** [comment]
Aw ok, I thought our default was an empty list in the config
skeleton: []
I'll account for both cases.

**Comment by MMathisLab** [comment]
I guess this is an edge case if someone deletes the "fake" skeleton that is put in by default, that is true ;)

**Comment by AlexEMG** [comment]
Yes, def. should be []. But better to cover both.

**Comment by jeylau** [comment]
Let me just also add the test for the paf graph and this will look good :)

**Review by MMathisLab — APPROVED** [review]
works great, thanks @jeylau !!!

**Comment by jeylau** [comment]
Please let me know if you feel the error is documented enough!

**Review by MMathisLab — COMMENTED** [review]
`bodypartnames = multianimalbodyparts + uniquebodyparts`

currently the SkeletonBuilder does not allow one to visualize and connect the unique bodyparts, which upon further conisderation, perhaps it should do; i.e. now it only shows the `multianimalbodyparts` but indeed the unique points "can" be connected, while the `multianimal` must be, correct @AlexEMG ?

so, here it's check for only multianimal bodyparts, but should we warn if any bodyparts (as defined in the code sniplet above) are not-connected?

**Comment by MMathisLab** [comment]
also small thing, but if it's `skeleton:` in the config.yaml, it doesn't print the warning, it just doesn't work ;). if it's `skeleton: [ ]` works nicely :)

**Comment by jeylau** [comment]
> also small thing, but if it's `skeleton:` in the config.yaml, it doesn't print the warning, it just doesn't work ;). if it's `skeleton: [ ]` works nicely :)

https://github.com/DeepLabCut/DeepLabCut/pull/717/commits/02e10fd114e3ae988836ff0e4b3791e263529e24 should handle that case, I've tested it :)

**Review by AlexEMG — APPROVED** [review]
Great!

**Pull request merged**
