### PR TITLE
Freshening up `Getlistofvideos`

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
re: https://github.com/DeepLabCut/DeepLabCut/issues/1703

* type hints & docstring update
* make `videotype` optional when given a list of files
* coerce strings to list at start
* use shuffle instead of sampling with list of videos
* don't change directory
* unify filtering into one operation at end of function

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
Noticing that one of the test builds is failing with the same error that my labmate is getting (and was the reason i started checking out the code today): https://github.com/DeepLabCut/DeepLabCut/runs/5311105347?check_suite_focus=true

```
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.

Processing...  /Users/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-02-23/videos/m3v1mp4short.mp4
  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 5/5 [00:00<00:00, 5804.46it/s]
/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py:671: UserWarning: No optimal solution found. Employing black magic...
  warnings.warn("No optimal solution found. Employing black magic...")

  0%|          | 0/4 [00:00<?, ?it/s]
100%|██████████| 4/4 [00:00<00:00, 5244.52it/s]
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 668, in stitch
    _, self.flow = nx.capacity_scaling(self.G)
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/networkx/algorithms/flow/capacityscaling.py", line 394, in capacity_scaling
    raise nx.NetworkXUnfeasible("No flow satisfying all demands.")
networkx.exception.NetworkXUnfeasible: No flow satisfying all demands.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 739, in stitch
    _, self.flow = nx.capacity_scaling(self.G)
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/networkx/algorithms/flow/capacityscaling.py", line 394, in capacity_scaling
    raise nx.NetworkXUnfeasible("No flow satisfying all demands.")
networkx.exception.NetworkXUnfeasible: No flow satisfying all demands.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/testscript_multianimal.py", line 168, in <module>
    use_shelve=USE_SHELVE,
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 365, in analyze_videos
    modelprefix=modelprefix,
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 1124, in stitch_tracklets
    stitcher.stitch()
  File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/stitch.py", line 748, in stitch
    f"Could not reconstruct {self.n_tracks} tracks from the tracklets given."
ValueError: Could not reconstruct 3 tracks from the tracklets given.
```

**Comment by sneakers-the-rat** [comment]
While i'm at it, it looks like there are a ton of places where `videotype='avi'` in derivative functions. Seems like odd default behavior (eg. a user giving a list of `.mp4` videos but forgetting to set the `videotype`). Seems like those should be `None` in wrapping functions. Another way that this could be done is to accept either a string or a tuple `('avi', 'mp4')`, and in the Getlistofvideos function have the default be a list of common/supported extensions, so if no `videotype` is provided it matches all video-like files.

**Review by MMathisLab — APPROVED** [review]

**Review by jeylau — APPROVED** [review]
Looks great Jonny, thank you!

**Comment by MMathisLab** [comment]
the failing build is just stochastic as there is so little data for this testing cc @jeylau can explain; but if you labmate is getting this, this means the network isn't trained enough typically

**Comment by sneakers-the-rat** [comment]
> the failing build is just stochastic as there is so little data for this testing cc @jeylau can explain; but if you labmate is getting this, this means the network isn't trained enough typically

ty i'll let them know :)

**Pull request merged**
