### PR TITLE
GUI fixes

### PR DESCRIPTION
**Pull request by KonradDanielewski**
I'm currently testing the GUI and trying to fix reported issues. One is more design improvement, i.e. being able to change the working dir also via textbox, not only by clicking the `Location` text (I think maybe it should stand out somehow - it doesn't indicate in any way that it's a button unless you hover over it)

Another thing I noticed was that label removal wasn't working in the tracklet toolbox, so also fixed that. Seems to work now.

Some other reported things that I didn't know if should be changed: 

- `Labelling GUI` button disabled by defualt in Extract Outlier Frames tab - what if you extracted before and are going back to refining?
- Manual extraction of frames still points to old GUI when called via `deeplabcut.extract_frames()`

### CODE REVIEW

**Comment by jeylau** [comment]
Thanks @KonradDanielewski! I agree that the Labeling GUI button should be enabled.
Do you want to address the `deeplabcut.extract_trames()` in this PR?

**Comment by KonradDanielewski** [comment]
Sure, I'll enable the button and pointing to napari in frame extraction today

**Comment by KonradDanielewski** [comment]
@jeylau So another reported issue is `QObject::startTimer: Timers can only be used with threads started with QThread` when using the player feature of the tracklet toolbox. If I understand correctly, the BackgroundPlayer class has to be made into a QObject and TrackletVisualizer class converted to work with a QThread that will run that QObject - I can also be entirely incorrect since it's my first time working with Qt

**Comment by jeylau** [comment]
Awesome, thanks @KonradDanielewski! Does the Timer issue prevent the tracklet GUI from running though?

**Comment by KonradDanielewski** [comment]
The tracklet GUI is running and the player even starts and stops albeit with some delay, but when you try to skip forward or backward with `alt+->`/`alt+<-` it does nothing and if tried a couple of times throws `Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:167` which ultimately crashes the whole GUI (tracklet and general one).

**Comment by KonradDanielewski** [comment]
I just noticed that the way I implemented the Location directory change is easily broken when the path isn't pasted first (every input into the Location textbox updates from all the textboxes). I'll see if I can fix this but if not it should be discarded from the pull request.

**Comment by KonradDanielewski** [comment]
Partially adresses #2161 - still haven't found out why the data from refinement isn't extracted and saved

**Comment by KonradDanielewski** [comment]
About the `Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:167` it's also happening in the older GUI when you try to move forward during the playback. I read a little more to try and understand this and I might have an idea. 

The `alt + left/right` works in an intended way, just producing a lot of warnings. If I understand correctly, all the things happening in the tracklet_toolbox are run multithreaded and somehow if this skip by one frame by just pressing an arrow key without `alt` happens during the video playback, the video read goes out of sync. So I guess it's more of an unexpected user input not being handled rather than anything else.

**Review by jeylau — APPROVED** [review]

**Comment by KonradDanielewski** [comment]
I removed the textbox based location change since it wasn't working properly

**Comment by jeylau** [comment]
@KonradDanielewski, I'm looking at https://github.com/DeepLabCut/DeepLabCut/issues/2152 separately. Is your PR ready otherwise?

**Comment by KonradDanielewski** [comment]
The rest works as intended - though one issue is not resolved completely - the refinement not extracting data and creating `machinelabels` file - but I'm not sure I can fix this one - to my eyes it all looks correct but for some reason doesn't work.

**Comment by KonradDanielewski** [comment]
OK, honest mistake. It doesn't export data cause there is no export in the `refine_tracklets.py`, only merge which doesn't do anything without the export.

**Comment by KonradDanielewski** [comment]
Fixed the refined tracklets data export and mutliindex creation. Also added handling for two pandas deprecation warnings

**Comment by KonradDanielewski** [comment]
Also fixed the `analyze_videos` tab since it wasn't working properly. I guess now the most obvious GUI bugs are fixed

**Comment by jeylau** [comment]
Sweet! I fixed the tracklet refinement GUI in #2191, so should be good to merge!

**Pull request merged**
