### PR TITLE
Add benchmark API

### PR DESCRIPTION
**Pull request by stes**
Add API to generate the table hosted on https://benchmark.deeplabcut.org

**Updates (29/10/22):**

- https://github.com/DeepLabCut/benchmark has been updated. The codebase there now uses `deeplabcut.benchmark` to compute the results hosted on https://benchmark.deeplabcut.org/
- Added docs: image

**TODO**

- [x] Verify results against maDLC reference results
- [x] Add docs?

### CODE REVIEW

**Review by MMathisLab — APPROVED** [review]

**Comment by stes** [comment]
This needs a few more additions before merging.

**Comment by MMathisLab** [comment]
@stes update?

**Comment by MMathisLab** [comment]
Could we please add a docs page in https://github.com/stes/DeepLabCut/tree/add-benchmark/docs? Even if it links to the benchmark for further details, should be findable under main docs :)

**Comment by MMathisLab** [comment]
@jeylau @AlexEMG bumping this:
>> Could we please add a docs page in https://github.com/stes/DeepLabCut/tree/add-benchmark/docs? Even if it links to the benchmark for further details, should be findable under main docs :)

**Comment by jeylau** [comment]
Looks good! One comment though: I'd add the DLCBenchMixin back in, to make it easier for us or DLC users to evaluate models. What do you think @stes?

**Comment by stes** [comment]
> @jeylau @AlexEMG bumping this:
> 
> > > Could we please add a docs page in https://github.com/stes/DeepLabCut/tree/add-benchmark/docs? Even if it links to the benchmark for further details, should be findable under main docs :)

Basic docs added, see updated description.

**Review by AlexEMG — APPROVED** [review]

**Pull request merged**
