### PR TITLE
Rename functions in `auxiliaryfunctions.py` from CamelCase to underscores

### PR DESCRIPTION
**Pull request by rahulporuri**
In this PR, we went through every function in the `deeplabcut.utils.auxiliaryfunctions` and renamed functions from CamelCase to underscores.

Each function was renamed and the function usage updated in a single commit so this PR can easily be reviewed one commit at a time.

Note that CamelCase aliases are added to the end of the module for backwards compatibility. I'm not sure how many people are using `deeplabcut` as a package and importing functions from inside the package. If backwards compatibility isn't a concern and the maintainers are sure that there is no need to maintain the aliases, I can remove them. If necessary, I can add `DeprecationWarning`s when the aliases are being used, if necessary.

### CODE REVIEW

**Comment by rahulporuri** [comment]
@jeylau @AlexEMG ^ one of the renaming PRs I had in mind

**Review by jeylau — APPROVED** [review]

**Comment by jeylau** [comment]
Looks good to me @rahulporuri, thanks a lot!

**Review by AlexEMG — APPROVED** [review]

**Comment by AlexEMG** [comment]
Thanks, maybe good to add `DeprecationWarning`s for the CamelCase functions.

**Comment by rahulporuri** [comment]
> Thanks, maybe good to add `DeprecationWarnings` for the CamelCase functions.

Sure. I'll try to add those soon.

**Comment by MMathisLab** [comment]
Is this backwards compatible though? It has to be backwards comp. to the 2.0 code base cc @jeylau

**Comment by jeylau** [comment]
@MMathisLab, yes, @rahulporuri handled it with the aliases added here https://github.com/DeepLabCut/DeepLabCut/blob/86d741ec713801b2436e393e3b336474797e9c23/deeplabcut/utils/auxiliaryfunctions.py#L817-L828

**Pull request merged**
