### PR TITLE
Fix NameError: name 'config' is not defined in get_track_method

### PR DESCRIPTION
**Pull request by jeylau**
`config` was undefined in the function, causing the error reported here https://forum.image.sc/t/track-method-parameter-is-missing-in-madlcs-analyze-videos-in-colab/62542.
Tracking methods are now also defined in a single location, making it easier to add new ones in the future.

### CODE REVIEW

**Review by AlexEMG — APPROVED** [review]
But not any track_method that is passed to analyze_videos should become the default... Default should just be the fallback, when nothing is passed. 

so let's just pass config to: 
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxfun_multianimal.py

**Comment by jeylau** [comment]
What lines are you referring to @AlexEMG?

**Comment by AlexEMG** [comment]
Sorry - https://github.com/DeepLabCut/DeepLabCut/pull/1665/files#diff-247e492d6453c803baf6192a6f5a923d60127334603814fc57df5cd810f4ca02L44

**Comment by AlexEMG** [comment]
Let's move the catch-clause of single body part to auxfun. Thanks! (and comment out why this case is important)

**Comment by MMathisLab** [comment]
fine now @AlexEMG ?

**Review by AlexEMG — APPROVED** [review]
Looks good, but please check logical flow again.

**Review by MMathisLab — APPROVED** [review]

**Pull request merged**
