### PR TITLE
simplified 1-click maDLC analyze video, track, create video within the GUI

### PR DESCRIPTION
**Pull request by MMathisLab**
# Goal:

To simplify GUI default maDLC into a single step: more advanced users should use the colab or terminal commands, but this makes it simple and straightforward for beginners. This PR directly addresses the GUI; as the one-step function was updated in #1567 , which now allows for dlc.analyze_videos(... `auto_track=True`) to complete analysis, stitching and tracking.

- Example of the new GUI layout for single-click maDLC: 
Screen Shot 2021-12-20 at 5 37 39 PM

## Done:

- [x] Analyze video tab now includes a "one-click" video analysis, create_full_detections_video, track+stitch (assuming same # of animals used in training).
Some dropped terms for simplification .. should decide if this is OKAY, or should make a depreciation warning as not fully backwards compatible (BC)? 
- [x] dropped: `video_type` as a selection menu (as the functions now work without passing this anyhow, so this is BC)
- [x] dropped: `trainingindex`: I suspect this is never changed from default 0... but, dropping could break someone's BC. 
- [x] dropped trainingindex in other tabs too
- [x] combined tab for extract outliers and label, simplifies workflow. 
- [x] filtering works + get CSV file for user
- [x] add in n_tracks, so people can pass in # of animals
- [x] more than 1 video selected working (thanks @backyardbiomech ! )
- [x] update how analyze_videos h5 to csv handles videos (thanks @AlexEMG)
- [x] plot_traj and plots pop up for saDLC and maDLC
- [x] able to use ID = true
- [x] able to use calibration = true
- [x] tested: all combinations of the tabs in the GUI for maDLC
- [x] enhancement: better print statement for `filenotfound` during video analysis to remind use to check iteration # in config.yaml too 
- [x] better network defaults for saDLC and maDLC; also dropped all the model options in the drop down in order to guide novice users to best options; left them all for model comparison though!

Here is the (minimal) expected output from the current WIP PR: 

```python
pythonw -m deeplabcut
Starting GUI...
DLC network loading and video analysis starting ...
Using snapshot-5 for model /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/dlc-models/iteration-0/multi_mouseSep3-trainset80shuffle1
/Users/mwmathis/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Activating extracting of PAFs
2021-12-20 15:26:18.987605: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Starting to analyze %  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
Video already analyzed! /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4shortDLC_dlcrnetms5_multi_mouseSep3shuffle1_5.h5
Using snapshot-5 for model /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/dlc-models/iteration-0/multi_mouseSep3-trainset80shuffle1
Processing...  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
Tracklets already computed /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4shortDLC_dlcrnetms5_multi_mouseSep3shuffle1_5_el.pickle
Set overwrite = True to overwrite.
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 15807.68it/s]
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Detections already plotted,  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4shortDLC_dlcrnetms5_multi_mouseSep3shuffle1_5_full.mp4
DLC network loading and video analysis starting ...
Using snapshot-5 for model /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/dlc-models/iteration-0/multi_mouseSep3-trainset80shuffle1
Activating extracting of PAFs
Starting to analyze %  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
Loading  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
Duration of video [s]:  1.03 , recorded with  30.0 fps!
Overall # of frames:  31  found with (before cropping) frame dimensions:  640 480
Starting to extract posture from the video(s) with batchsize: 8
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:16<00:00,  1.89it/s]
Video Analyzed. Saving results in /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos...
Using snapshot-5 for model /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/dlc-models/iteration-0/multi_mouseSep3-trainset80shuffle1
Processing...  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
Analyzing /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4shortDLC_dlcrnetms5_multi_mouseSep3shuffle1_5.h5
31it [00:00, 623.82it/s]
31it [00:03,  8.74it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  /Users/mwmathis/Documents/DeepLabCut/examples/multi_mouse-dlc_team-2021-09-03/videos/m3v1mp4short.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 53773.13it/s]
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Creating labeled video for  m3v1mp4short
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 268.20it/s]
```

### CODE REVIEW

**Comment by backyardbiomech** [comment]
This looks great. I tried running (maDLC model but trained for single animal) on three videos selected simultaneously, and it worked without any obvious problems (i.e. detection videos look good), so I would check that box. I could also load and view data with refine tracks tab.

I did **not** get an unfiltered csv when that option was checked, with or without filtering on (I did get a filtered csv when requested). 

Thought: if n_tracks == 1, and `len(individuals)==1` in config.yaml, it can be assumed that the model was only ever trained on single animal videos, and that `use ID` was always false (or irrelevant), so that option could be grayed out? Would this also be true for `calibrate animal assembly`? Fewer options are less confusing for users.

**Comment by MMathisLab** [comment]
https://github.com/DeepLabCut/DeepLabCut/pull/1621/commits/920f121eeb6166c64a3f3809781e46ec7a804143 further removes the trainingindex from other tabs! It also simplifies the extract outliers and labeling into a single tab, and OPTIONAL tabs are clearly marked "OPT: ..." 

new merged tab & overall layout tab change:

Screen Shot 2021-12-21 at 3 53 12 PM



Note: This was tested on **single animal projects** and working very well (extract, label, train, evaluate, analysis video(s), plot_traj, outlier with jump or uncertain, refine labels, and merge --> jumps back to create training set tab 
- [x]  minor issue with manual extract outliers, getting a `numpy.int64` error that I will debug. --> https://github.com/DeepLabCut/DeepLabCut/pull/1622
- [x] test on multi-animal project

**Comment by MMathisLab** [comment]
>> I did not get an unfiltered csv when that option was checked, with or without filtering on (I did get a filtered csv when requested).

@backyardbiomech fixed! now this works, and even if one first runs with no checked, clicking run again will still convert. I added some other things (see main post), and have a few things left to clean up, but getting closer! thanks again for the feedback.

**Comment by MMathisLab** [comment]
@backyardbiomech I considered the greying out, but here is my thoughts, happy for your feedback:

-  if I read from config.yaml n=1, someone who trained a single animal but in multi-mode *could* still use that model for >1 animal; this is actually akin to our demo in Mathis 2018, where we show for pose even if trained on one, you get a universal detector for these points: 
Screen Shot 2021-12-22 at 8 10 59 AM

- If I need to read from the selected # then grey out, it's a bit tedious on the backend, and given this is my "last attempt" at this wxPython GUI, not sure it's worth another day. If they use calibration, fine, if they for some reason set ID= true and then have more than 1 mouse, also useable. I can recipe this out vs. editing / some might want to used the potential greyed-out features. 

Let me know if that sounds okay for you?

**Comment by MMathisLab** [comment]
okay, all combinations tested across both single animal and multi-animal projects; see top post for final status. Ready for review.

**Comment by backyardbiomech** [comment]
> Let me know if that sounds okay for you?

@MMathisLab , I hadn't thought of the one to many possibility. Looks good to me!

**Review by jeylau — APPROVED** [review]

**Comment by jeylau** [comment]
Looks good to me too ☺️

**Review by backyardbiomech — APPROVED** [review]

**Pull request merged**
