### PR TITLE
3.8* support / dependency clean up [WIP]

### PR DESCRIPTION
**Pull request by MMathisLab**
a few dependencies are drop as they were dep of dep; note moviepy is also dropped, but this might be required (seems not required to run `testscipt.py` and `testscript_multianimal.py` which pass successfully). 

- note, this also includes updating the conda files to TF 1.15.5 vs. 1.13.1; then numpy 1.17.3 is supported/no warnings.
- this has only been tested on MacOS; I would ask @AlexEMG to test on ubuntu and @jeylau on windows before committing. 
- also only tested on CPU MacOS; GPU support should be tested w/TF 1.15.5
- note 3.7 is still required, given the TF limitations given in issues #1124, but at least now DLC package does build in 3.8; meaning we are getting away from pip dependency issues :)

### CODE REVIEW

**Comment by MMathisLab** [comment]
@jeylau this is failing now: https://github.com/DeepLabCut/DeepLabCut/runs/1995719243#step:6:14

**Comment by jeylau** [comment]
Yep, we have to install deeplabcut. But I'm looking for ways around it.

**Comment by MMathisLab** [comment]
okat @jeylau I added back moviepy and this is passing. I didn't go through all your changes (it's a lot ;P); can you confirm this runs all the test scripts? (and run black)

**Comment by MMathisLab** [comment]
@jeylau TF 1.x is not supported in 3.8 python ;/. we we can only test the installation of DLC w/o TF https://www.tensorflow.org/install/pip#system-requirements

**Comment by MMathisLab** [comment]
we should run black ;) when I ran it on your edits it required 40 files to be changed btw!

**Comment by jeylau** [comment]
Aw I forgot! :/ That's something I wanted to add to the workflow as well...

**Pull request merged**
