### PR TITLE
SpinCtrl widget now accepts a value of 1

### LINKED ISSUE #1291: Cannot reconstruct 1 animal track in refinement GUI
You will have to update to rc2; 1 did not support single animal mode.

_Originally posted by @MMathisLab in https://github.com/DeepLabCut/DeepLabCut/issues/1288#issuecomment-851565226_

### PR DESCRIPTION
**Pull request by jeylau**
Fixes #1291

### CODE REVIEW

**Review by MMathisLab — APPROVED** [review]

**Comment by DaBue93** [comment]
If I use deeplabcut.stitch_tracklets() I get the following error:

stitching

is there a error in my approach?

**Comment by jeylau** [comment]
Your configuration file is missing the key `individuals`, please make sure you haven't deleted it or changed the configuration format. Also note that `min_length=3` looks really low to me: this is telling DeepLabCut that you do not want tracklets separated by more than 3 frames to be possibly connected together. Just be aware that stitching may fail as a result, although you'd get warned if that's the case. It is often desirable to leave it to `None`, so it is up to DLC to detemine what's best. ☺️

**Comment by DaBue93** [comment]
According to the corresponding csv file, the series 'individuals' is present.

stitching_csv

**Comment by jeylau** [comment]
It's missing in your configuration file (the config.yaml), not the CSV.

**Comment by DaBue93** [comment]
You are right, thanks for that hint :) no i get the following output:

stitching_1 indiv

it seems, the second animal coords were cropped

i will try to adjust the parameters inside the bracket

**Comment by DaBue93** [comment]
is there a way to merge the two "animals" to one? that a continuous blue ine can be seen again during refinement? i tried n_tracklets=0/1/2/3. didnt work.

**Pull request merged**
