### PR TITLE
Model Zoo new API

### PR DESCRIPTION
**Pull request by MMathisLab**
- new API for running inference 
- video adaptation tools

### CODE REVIEW

**Comment by jeylau** [comment]
Conflicts fixed!

**Review by jeylau — APPROVED** [review]

**Review by jeylau — APPROVED** [review]
Logging is silent though; cannot figure out why...

**Comment by jeylau** [comment]
I'm rewriting the scale averaging as it is currently very slow, and it's then ready to merge ☺️

**Comment by MMathisLab** [comment]
LGTM; @AlexEMG any thoughts?

**Review by AlexEMG — APPROVED** [review]
tools shouldn't be deleted.

**Pull request merged**
