### PR TITLE
Fix docstrings

### PR DESCRIPTION
**Pull request by ghost**
This fixes a lot of docstrings to keep them clean, consistent, and comprehensive.

It does not completely fix the docstrings of cli.py, and it does not touch the docs themselves.

### CODE REVIEW

**Comment by AlexEMG** [comment]
Thanks for your input! I will look at this, once I have some idle time.

**Review by AlexEMG — DISMISSED** [review]

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
okay, I am fine with the changes now. I don't love "str" as it is not clear to novice programmers that it means string.

**Comment by ghost** [comment]
That's true, although I like `str` for accuracy.

**Comment by ghost** [comment]
Perhaps we could keep `str` for docstrings to stay consistent with python docstring conventions (i.e. numpy, Google, reST, etc.) which would keep them compatible with documentation generation programs (e.g. Sphinx) and other tools in the python ecosystem. Meanwhile the user docs could be more novice friendly. I'm thinking that a novice that does not know what `str` is probably does not know about docstrings and how to view them either.

**Comment by MMathisLab** [comment]
I think actually a lot of users check the docstrings, as we sugest that for every function in DLC if they type `?` afterwards, i.e. `deeplabcut.create_new_project?` they can get help :)

**Comment by ghost** [comment]
Ah, fair point.

**Comment by ghost** [comment]
What about cli.py? It still has `str`, was that intentional?

**Comment by ghost** [comment]
Can we please get this merged before further conflicts arise?

**Review by MMathisLab — COMMENTED** [review]
added back information under analyzie_videos

**Comment by MMathisLab** [comment]
sorry, @UnicodeAlt255 - we had so many function changes, but I can work through these merge issues... I think 2.0.4 is our best package yet though!

**Pull request closed without merging**
