### PR TITLE
WIP: Modernize conda environment

### PR DESCRIPTION
**Pull request by gdevenyi**
Remake conda environment using the dev environment in #340 and then re-exporting to have specific versions.

This fixes the tons of packages install by pip *and* the fact that the old environment was installing things and then upgrading them with pip.

### CODE REVIEW

**Comment by gdevenyi** [comment]
These could also now be renamed as they're by-no-means ubuntu restricted. This is the beauty of using conda packages everywhere.

**Comment by gdevenyi** [comment]
So, technically speaking, you only need *one* conda environment. These file should work everywhere.

I have no Windows or OSX to test.

**Comment by MMathisLab** [comment]
Yeah, I will leave the others as options still, as for some reason we did hit some cross-platform issues last year.

**Comment by DenisPolygalov** [comment]
Getting rid of the pip-based packages is only half of the solution. Another half is to keep strictly single (default) conda package distribution channel, i.e. get rid of the 'conda-forge'. The TensorFlow nowadays is also distributed within 'conda install', so don't need to install system-side stuff like cudatoolkit. At least on Windows. The only package that is absent in default conda channel is 'easydict'. After replacing 'ruamel.yaml' in the utils/auxiliaryfunctions.py with 'ruamel_yaml' DeepLabCut can be simply installed like this:
> conda create -n dlc
> activate dlc
> conda install tensorflow-gpu, matplotlib, wxpython, opencv, pandas, tqdm, yaml, PyYaml
> conda install ruamel_yaml, scikit-image, scikit-learn, statsmodels, click, pytables
> pip install easydict
Without using BS like Docker, pip or enforcing users to install older version of packages as dependencies.

**Comment by MMathisLab** [comment]
Well, unfortunately that’s not quite the full story as dlc has several dependencies that need to be version fixed... also Docker is not BS ;)

**Pull request merged**
