### PR TITLE
Transition from wxpython to PySide2 project management GUI

### PR DESCRIPTION
**Pull request by jeylau**
This PR presents a new project management GUI and labeling, re-refining, and video GUIs.

- NOTE, this PR will therefore drop support for python 3.7 due to python 3.8 requirements for dlc-napari gui. This could cause issues for macbook M1 chip users, as our conda file for M1 currently relies on 3.7 and thus will need modifications*:

### To test this branch, please git clone the repo and run `git checkout new_gui`. 

Built a test env:
`conda create --name DEEPLABCUT_newGUI python=3.9`

then activate the env. `conda activate DEEPLABCUT_newGUI`

Then run:

`pip install --upgrade --force-reinstall -e '.[gui]'`

then to launch the GUI: 

`python -m deeplabcut`

### Macbook M1 users (experimental): 

first please download:

```
# DeepLabCut M1 environment instructions:
# For the M1 chip, please first download the Rosetta wheel for tensorflow 2.4.1:
# https://drive.google.com/file/d/17pSwfoNuyf3YR8vCaVggHeI-pMQ3xL7l/view?usp=sharing
```
then run: 
```bash
❯ conda create --prefix=/opt/anaconda3/envs/DEEPLABCUT_newGUI python=3.8
❯ conda activate /opt/anaconda3/envs/DEEPLABCUT_newGUI
❯ cd
❯ cd Downloads
❯ pip install tensorflow-2.4.1-py3-none-any.whl --no-dependencies --force-reinstall
Processing ./tensorflow-2.4.1-py3-none-any.whl
Installing collected packages: tensorflow
Successfully installed tensorflow-2.4.1
❯ cd
❯ cd Documents/DeepLabCut
❯ pip install -e '.[gui]'
```
TODOs:

- [x] fix failing build: 
```
/opt/hostedtoolcache/Python/3.9.13/x64/deeplabcut
      copying deeplabcut/gui/media/logo.png -> /opt/hostedtoolcache/Python/3.9.13/x64/deeplabcut
      copying deeplabcut/gui/media/dlc_1-01.png -> /opt/hostedtoolcache/Python/3.9.13/x64/deeplabcut
      error: can't copy 'deeplabcut/gui/assets/*.png': doesn't exist or not a regular file
      [end of output]
```
- [x] create_training_dataset not actually creating a training dataset from GUI tab.
- [x] kmeans runs and hangs for a long time; then crashes GUI (macOS 12.5.1 non-M1 chip)

### CODE REVIEW

**Comment by jeylau** [comment]
@MMathisLab, I followed the instructions above (new env w/ py3.10) and had no problem with either clustering or dataset creation (both with single- and multi-animal projects) 🤔
`conda env create -f conda-environments/DEEPLABCUT.yaml` does not work for me though, installing dependencies never completes.

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
seems across PRs create_video is failing; must be a new change? 

```
4m 40s
Tracklets created...
Processing...  /home/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-10-04/videos/m3v1mp4short.mp4
100%|██████████| 3/3 [00:00<00:00, 48026.38it/s]
Plotting trajectories...
Loading  /home/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-10-04/videos/m3v1mp4short.mp4 and data.
Plots created! Please check the directory "plot-poses" within the video directory
Trajectory plotted.
Creating labeled video...
Starting to process video: /home/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-10-04/videos/m3v1mp4short.mp4
Loading /home/runner/work/DeepLabCut/DeepLabCut/multi_mouse-dlc_team-2022-10-04/videos/m3v1mp4short.mp4 and data.
Duration of video [s]: 1.03, recorded with 30.0 fps!
Overall # of frames: 31 with cropped frame dimensions: 640 480
Generating frames and creating video.

  0%|          | 0/31 [00:00<?, ?it/s]
  0%|          | 0/31 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 721, in proc_video
    _create_labeled_video(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 796, in _create_labeled_video
    CreateVideo(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 168, in CreateVideo
    color = colors[num_ind]
IndexError: index 6 is out of bounds for axis 0 with size 4
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/testscript_multianimal.py", line 200, in <module>
    deeplabcut.create_labeled_video(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/deeplabcut/utils/make_labeled_video.py", line 580, in create_labeled_video
    pool.map(func, Videos)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: index 6 is out of bounds for axis 0 with size 4
```

**Review by AlexEMG — COMMENTED** [review]
Looks good, data shouldn't be deleted. Will fix.

**Comment by MMathisLab** [comment]
I suggest we merge and make a rc1 release; I can confirm this works beautifully on my preM1 build for now :)

**Comment by backyardbiomech** [comment]
I installed using the instructions at the top, on Windows, without a problem. Quickly opened an existing project.
A couple of notes:
1. A built in quick config editor?! This is great. VERY SMALL bug/issue: If I expand an item (e.g. video_sets), I can't see the Value column for any of the other items until I collapse that set. There might not be anything you can do about it.
2. **Label Frames**: Selected a folder to label, but no window opened. Got the following error in terminal: 

<details>

```
Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Documents\repos\DeepLabCut\deeplabcut\gui\tabs\label_frames.py", line 45, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\jacksonbe3\Documents\repos\DeepLabCut\deeplabcut\gui\widgets.py", line 28, in launch_napari
    viewer = napari.Viewer()
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\_lazy.py", line 47, in __getattr__
    submod = import_module(f'{module_name}.{attr_to_modules[name]}')
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\components\__init__.py", line 24, in <module>    
    from . import _viewer_key_bindings  # isort:skip
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\components\_viewer_key_bindings.py", line 9, in <module>
    from .viewer_model import ViewerModel
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\components\viewer_model.py", line 34, in <module>    from ..plugins.utils import get_potential_readers, get_preferred_reader
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\plugins\__init__.py", line 10, in <module>       
    from ._plugin_manager import NapariPluginManager
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\plugins\_plugin_manager.py", line 34, in <module>    from . import _builtins, hook_specifications
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\plugins\_builtins.py", line 18, in <module>      
    from ..utils.io import (
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\utils\io.py", line 27, in <module>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\napari\utils\io.py", line 27, in <setcomp>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\imageio\core\format.py", line 640, in <genexpr>
    return iter(x.format for x in self._formats)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\imageio\config\plugins.py", line 85, in format
    module = importlib.import_module(self.module_name, self.package_name)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\lib\site-packages\imageio\plugins\ffmpeg.py", line 136, in <module>       
    import imageio_ffmpeg
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newGUI\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'imageio_ffmpeg'
```
</details>
Fixed with `pip install imageio-ffmpeg`

4. Napari window opened, but  I got a pytables error. tables had been installed in the env with pip, ran `conda install pytables` - which of course also "updated" numpy and other modules.
5.  After that, napari window opens and image shows, but no data points show (these are already labeled). with the following traceback.
<details>

```python
Traceback (most recent call last):
  File "C:\Users\jacksonbe3\Documents\repos\DeepLabCut\deeplabcut\gui\tabs\label_frames.py", line 45, in label_frames
    _ = launch_napari(folder)
  File "C:\Users\jacksonbe3\Documents\repos\DeepLabCut\deeplabcut\gui\widgets.py", line 35, in launch_napari
    viewer.open(files, plugin='napari-deeplabcut')
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\components\viewer_model.py", line 931, in open   
    self._add_layers_with_plugins(
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\components\viewer_model.py", line 1160, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\components\viewer_model.py", line 1234, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\components\viewer_model.py", line 5, in add_points
    import os
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\components\layerlist.py", line 135, in insert    
    super().insert(index, new_layer)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\utils\events\containers\_selectable_list.py", line 65, in insert
    super().insert(index, value)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\utils\events\containers\_evented_list.py", line 183, in insert
    self.events.inserted(index=index, value=value)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\utils\events\event.py", line 757, in __call__    
    self._invoke_callback(cb, event if pass_event else None)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\utils\events\event.py", line 794, in _invoke_callback
    _handle_exception(
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari\utils\events\event.py", line 781, in _invoke_callback
    cb(event)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari_deeplabcut\_widgets.py", line 435, in on_insert  
    self._remap_frame_indices(layer_)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\napari_deeplabcut\_widgets.py", line 379, in _remap_frame_indices
    data[:, 0] = np.vectorize(temp.get)(data[:, 0])
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\numpy\lib\function_base.py", line 2328, in __call__     
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\numpy\lib\function_base.py", line 2406, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui\lib\site-packages\numpy\lib\function_base.py", line 2362, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set
```
</details>
I can confirm there are data in `CollectedData`, but it is the "old" file path format. Maybe that's the problem?

It is not. I ran it on the output of testscript.py and got the same error on both `reachingvideo` (old format of CollectedData) and `reachingvideoshort` (new format of CollectedData). 

env build details:
<details>

```
# packages in environment at C:\Users\jacksonbe3\Miniconda3\envs\DEEPLABCUT_newgui:
#
# Name                    Version                   Build  Channel
absl-py                   1.2.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl
blosc                     1.21.0               h19a0ad4_1
build                     0.8.0                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2022.07.19           haa95532_0
cachetools                5.2.0                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
certifi                   2022.9.14        py39haa95532_0
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dask                      2022.9.2                 pypi_0    pypi
dask-image                2022.9.0                 pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deeplabcut                2.2.2                     dev_0    <develop>
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               22.9.24                  pypi_0    pypi
fonttools                 4.37.4                   pypi_0    pypi
freetype-py               2.3.0                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.49.1                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hdf5                      1.12.0               h1756f20_0
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2
idna                      3.4                      pypi_0    pypi
imageio                   2.22.1                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.16.0                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter-client            7.3.5                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libclang                  14.0.6                   pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1
lzo                       2.10                 he774522_2
magicgui                  0.5.1                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
mock                      4.0.3              pyhd3eb1b0_0
msgpack                   1.0.4                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
napari                    0.4.16                   pypi_0    pypi
napari-console            0.0.6                    pypi_0    pypi
napari-deeplabcut         0.0.6                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.8.7                    pypi_0    pypi
npe2                      0.6.1                    pypi_0    pypi
numba                     0.56.2                   pypi_0    pypi
numexpr                   2.8.3            py39hb80d3ca_0
numpy                     1.23.3                   pypi_0    pypi
numpy-base                1.23.1           py39hca35cd5_0
numpydoc                  1.4.0                    pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.3.0                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pep517                    0.13.0                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pint                      0.19.2                   pypi_0    pypi
pip                       22.2.2           py39haa95532_0
prompt-toolkit            3.0.31                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
psygnal                   0.4.2                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9            py39haa95532_0
pyrsistent                0.18.1                   pypi_0    pypi
pyside2                   5.15.2.1                 pypi_0    pypi
pytables                  3.7.0            py39h9d4cd68_0
python                    3.9.13               h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
pytomlpp                  1.0.11                   pypi_0    pypi
pytz                      2022.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qdarkstyle                3.1                      pypi_0    pypi
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
setuptools                59.8.0                   pypi_0    pypi
shapely                   1.8.4                    pypi_0    pypi
shiboken2                 5.15.2.1                 pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
slicerator                1.1.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    5.2.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.3               h2bbff1b_0
stack-data                0.5.1                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
superqt                   0.3.5                    pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.27.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.8.12                pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     1.12.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.4.0                    pypi_0    pypi
typer                     0.6.1                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022c                h04d1e81_0
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vispy                     0.10.0                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
wrapt                     1.14.1                   pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h8cc25b3_3
zstd                      1.5.2                h19a0ad4_0
```
</details>

Unfortunately, I don't have the time right now to try fiddling with the build, but if anyone has some suggestions I'd be happy to try.

**Comment by jeylau** [comment]
Thanks @backyardbiomech! I'll see what may have happened and fix these 🐛.

**Comment by MMathisLab** [comment]
Hey @backyardbiomech thanks again so much! I added imageio-ffmpeg to setup now, to be doubly sure, and also the force-install; I have no issues opening the demo data with the gui, etc, so maybe try an install again now to see if fine? 


EDITS TO DO:

@jeylau minor comment, but the "check labels" button is gone from label tab; let's add that back as it's an optional step in user guide (although I agree now just flipping rapidly through images in napari GUI is much better/faster)

I also don't like that now one HAS to save before you can quit the labeling aspect; sometimes one makes a mistake and it's easier to just close and re-start, but now it forces me to save. I would like the warning once, but then allow me to close the napari-labeling GUI.

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
Failing to install on Ubuntu 20.04

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/userdlc/anaconda3/envs/DEEPLABCUT_newGUI/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
> 
[DLCv2.3Fail.txt](https://github.com/DeepLabCut/DeepLabCut/files/9815172/DLCv2.3Fail.txt)

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
> Failing to install on Ubuntu 20.04
> 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/userdlc/anaconda3/envs/DEEPLABCUT_newGUI/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Same behavior on separate computer (hardware) with Ubuntu 22.04

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
I suspect it may have to do with open-cv-python and open-cv-python-headless both being installed, but I can't seem to figure out a configuration that works.

**Pull request merged**
