### PR TITLE
Skip extracted videos

### PR DESCRIPTION
**Pull request by sin-mike**

### CODE REVIEW

**Comment by MMathisLab** [comment]
Hi @sin-mike can you please fill in the requested info for contributions (see here: https://github.com/DeepLabCut/DeepLabCut/blob/master/CONTRIBUTING.md) 

also, `userfeedback=True` does the same, i.e. skipped already extracted if user says `no`

**Comment by jeylau** [comment]
Hey @sin-mike, to avoid the addition of another keyword argument, we felt that passing `userfeedback='auto'` could be a good alternative; what do you think?

**Comment by jeylau** [comment]
@MMathisLab, should we close it? Or go for the 'auto' argument we had discussed back then?

**Comment by MMathisLab** [comment]
I guess close

**Pull request closed without merging**
