### PR TITLE
fliplr augmentation for single animal

### PR DESCRIPTION
**Pull request by biol-jsh**
Added the fliplr augmentation for the single animal augmentation.

### CODE REVIEW

**Comment by MMathisLab** [comment]
great, could you post some metrics on performance with this aug type in the main PR comment? Looks exciting! #AIResident :)

**Comment by biol-jsh** [comment]
> great, could you post some metrics on performance with this aug type in the main PR comment? Looks exciting! #AIResident :)

Yes, but those metrics won't be available until Monday.

**Comment by biol-jsh** [comment]
Training was interrupted in the weekend but for the first case I've tested (half of the training data, OOD i.e. no refining), the pixel error went down with around 2.7 px (average for 50k and 100k iterations) without pcut and around 1.5 px with pcut 0.6. So it seems to be working. Haven't done any statistics yet but will tomorrow.

**Review by jeylau — APPROVED** [review]

**Comment by jeylau** [comment]
Looks good to me, thanks @biol-jsh!

**Comment by MMathisLab** [comment]
@jeylau default will be false, right? but let's benchmark on classic DLC openField dataset, just for ease of mind

**Comment by jeylau** [comment]
@MMathisLab, that's right! It will only be used if a user specifies fliplr and symmetric_pairs in the pose_cfg.

**Comment by MMathisLab** [comment]
we want to merge, right? not closed on purpose @biol-jsh ?

**Comment by Tetra-quark** [comment]
@biol-jsh I just need a clarification: Does this augmentation both flip the image and swap the symmetric label pairs in training? Effectively doubling the training samples and resulting in the left and right being learnt as distinct from each other? (Or conversely does it make left and right indistinguishable?)

**Comment by biol-jsh** [comment]
@Tetra-quark Hi! It is to improve the network's ability to tell left from right. I'm not sure if it doubles the amount of training data, but in essence, yes, it flips both symmetrical pairs and the image. Imagine that you train on several videos of a dog walking from the left to the right. Then you want to analyze a video of a dog going from the right to the left. The network would typically struggle with that and confuse left and right. But by augmenting with fliplr, your network will train on videos (and labels) that are flipped so that the dogs walk from the right to the left as well, and therefore do better at telling left from right. See ["Balancing bats", DeepLabCut Blog, Aug 31, 2022](https://deeplabcut.medium.com/balancing-bats-d3c5bcfb71e1) for an example of how it can help.

**Comment by Tetra-quark** [comment]
@biol-jsh Thanks so much! Really happy to see this feature.

**Pull request merged**
