### PR TITLE
Delay disabling eager execution on tensorflow

### LINKED ISSUE #1906: Avoid calling disable eager computation at top level import
DeepLabCut seems to call `disable_eager_computation` from tensorflow at import time.

This creates some surprising behavior for those that expect eager computation to be enabled.

**Describe the solution you'd like**

* DeepLabCut to support eager computation. (Hard)
* Delay disabling eager computation until DeepLabCut actually needs it (patch below)

<details> <summary> Patch </summary>

```patch
diff --git a/deeplabcut/pose_estimation_tensorflow/core/evaluate.py b/deeplabcut/pose_estimation_tensorflow/core/evaluate.py
index 2851f7e..dbf0a4e 100644
--- a/deeplabcut/pose_estimation_tensorflow/core/evaluate.py
+++ b/deeplabcut/pose_estimation_tensorflow/core/evaluate.py
@@ -594,6 +594,7 @@ def evaluate_network(
                 "TF_CUDNN_USE_AUTOTUNE"
             ]  # was potentially set during training
 
+        tf.compat.v1.disable_eager_execution()
         tf.compat.v1.reset_default_graph()
         os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"  #
         #    tf.logging.set_verbosity(tf.logging.WARN)
@@ -916,6 +917,7 @@ def evaluate_network(
                                 foldername,
                             )  # Rescaling coordinates to have figure in original size!
 
+                        tf.compat.v1.disable_eager_execution()
                         tf.compat.v1.reset_default_graph()
                         # print(final_result)
                     else:
diff --git a/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py b/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
index d327690..3e22b57 100644
--- a/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
+++ b/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
@@ -123,6 +123,7 @@ def evaluate_multianimal_full(
         del os.environ["TF_CUDNN_USE_AUTOTUNE"]  # was potentially set during training
 
     tf.compat.v1.reset_default_graph()
+    tf.compat.v1.disable_eager_execution()
     os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"  #
     if gputouse is not None:  # gpu selectinon
         os.environ["CUDA_VISIBLE_DEVICES"] = str(gputouse)
@@ -556,6 +557,7 @@ def evaluate_multianimal_full(
                         )
 
                         tf.compat.v1.reset_default_graph()
+                        tf.compat.v1.disable_eager_execution()
 
                     n_multibpts = len(cfg["multianimalbodyparts"])
                     if n_multibpts == 1:
diff --git a/deeplabcut/pose_estimation_tensorflow/core/predict.py b/deeplabcut/pose_estimation_tensorflow/core/predict.py
index 04e4ac2..eebdc3d 100644
--- a/deeplabcut/pose_estimation_tensorflow/core/predict.py
+++ b/deeplabcut/pose_estimation_tensorflow/core/predict.py
@@ -30,6 +30,7 @@ from .openvino.session import OpenVINOSession
 
 def setup_pose_prediction(cfg, allow_growth=False, collect_extra=False):
     tf.compat.v1.reset_default_graph()
+    tf.compat.v1.disable_eager_execution()
     inputs = tf.compat.v1.placeholder(
         tf.float32, shape=[cfg["batch_size"], None, None, 3]
     )
@@ -216,6 +217,7 @@ def getposeNP(image, cfg, sess, inputs, outputs, outall=False):
 ### Code for TF inference on GPU
 def setup_GPUpose_prediction(cfg, allow_growth=False):
     tf.compat.v1.reset_default_graph()
+    tf.compat.v1.disable_eager_execution()
     inputs = tf.compat.v1.placeholder(
         tf.float32, shape=[cfg["batch_size"], None, None, 3]
     )
diff --git a/deeplabcut/pose_estimation_tensorflow/core/train.py b/deeplabcut/pose_estimation_tensorflow/core/train.py
index b8de950..496a5e5 100644
--- a/deeplabcut/pose_estimation_tensorflow/core/train.py
+++ b/deeplabcut/pose_estimation_tensorflow/core/train.py
@@ -19,7 +19,6 @@ from pathlib import Path
 
 import tensorflow as tf
 
-tf.compat.v1.disable_eager_execution()
 import tf_slim as slim
 
 from deeplabcut.pose_estimation_tensorflow.config import load_config
@@ -200,6 +199,7 @@ def train(
         max_to_keep=max_to_keep
     )  # selects how many snapshots are stored, see https://github.com/AlexEMG/DeepLabCut/issues/8#issuecomment-387404835
 
+    tf.compat.v1.disable_eager_execution()
     if allow_growth:
         config = tf.compat.v1.ConfigProto()
         config.gpu_options.allow_growth = True
diff --git a/deeplabcut/pose_estimation_tensorflow/predict_videos.py b/deeplabcut/pose_estimation_tensorflow/predict_videos.py
index ff42709..350ff7e 100644
--- a/deeplabcut/pose_estimation_tensorflow/predict_videos.py
+++ b/deeplabcut/pose_estimation_tensorflow/predict_videos.py
@@ -96,6 +96,7 @@ def create_tracking_dataset(
     if gputouse is not None:  # gpu selection
         os.environ["CUDA_VISIBLE_DEVICES"] = str(gputouse)
 
+    tf.compat.v1.disable_eager_execution()
     tf.compat.v1.reset_default_graph()
     start_path = os.getcwd()  # record cwd to return to this directory in the end
 
@@ -424,6 +425,7 @@ def analyze_videos(
     if gputouse is not None:  # gpu selection
         os.environ["CUDA_VISIBLE_DEVICES"] = str(gputouse)
 
+    tf.compat.v1.disable_eager_execution()
     tf.compat.v1.reset_default_graph()
     start_path = os.getcwd()  # record cwd to return to this directory in the end
 
@@ -1216,6 +1218,7 @@ def analyze_time_lapse_frames(
     if gputouse is not None:  # gpu selection
         os.environ["CUDA_VISIBLE_DEVICES"] = str(gputouse)
 
+    tf.compat.v1.disable_eager_execution()
     tf.compat.v1.reset_default_graph()
     start_path = os.getcwd()  # record cwd to return to this directory in the end
 
diff --git a/deeplabcut/pose_estimation_tensorflow/training.py b/deeplabcut/pose_estimation_tensorflow/training.py
index 7998c6f..5c9842e 100644
--- a/deeplabcut/pose_estimation_tensorflow/training.py
+++ b/deeplabcut/pose_estimation_tensorflow/training.py
@@ -125,6 +125,7 @@ def train_network(
 
     from deeplabcut.utils import auxiliaryfunctions
 
+    tf.compat.v1.disable_eager_execution()
     tf.compat.v1.reset_default_graph()
     start_path = os.getcwd()
 
diff --git a/deeplabcut/pose_estimation_tensorflow/visualizemaps.py b/deeplabcut/pose_estimation_tensorflow/visualizemaps.py
index fb3f2da..8dc1daa 100644
--- a/deeplabcut/pose_estimation_tensorflow/visualizemaps.py
+++ b/deeplabcut/pose_estimation_tensorflow/visualizemaps.py
@@ -69,6 +69,7 @@ def extract_maps(
     import numpy as np
 
     tf.compat.v1.reset_default_graph()
+    tf.compat.v1.disable_eager_execution()
     os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"  #
     #    tf.logging.set_verbosity(tf.logging.WARN)

```
</details>
I can run the test suite (in random order) with this, but I feel like there might be something missing.

Related issue: https://github.com/DeepLabCut/DeepLabCut/issues/1112

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/DeepLabCut/DeepLabCut/issues/1906

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I am alot less happy with the patch now. it is much less contained and I feel like it is more intruisive.

**Comment by MMathisLab** [comment]
hey @hmaarrfk shall we close or revisit? :)

**Comment by hmaarrfk** [comment]
I guess I'm not too sure what your roadmap is.

We are trying to make the v1 -> v2 migration. Would you accept PRs toward that?

I think that might be "easier" to trying to set the different modes of tensorflow.

If you aren't planning on doing the tensorflow v1->v2 migration, than I can look back into this.

**Comment by MMathisLab** [comment]
Hey @hmaarrfk not sure I follow; we support TF2 now 
- our roadmap is to replace TF with PyTorch though for sure :)

**Comment by hmaarrfk** [comment]
> we support TF2 now

is a rather loose statement. 

The issues explained in the original issue I opened: https://github.com/DeepLabCut/DeepLabCut/issues/1906
outline how importing deeplabcut conflicts with other software that uses certain features of tensorflow 2. 

Specifically, this line of code here wants to use `v1` semantics.
https://github.com/DeepLabCut/DeepLabCut/blob/83d2e9ce39c69a3e58f96e482b15600d4dc7ac8b/deeplabcut/pose_estimation_tensorflow/core/predict.py#L56

```
    if allow_growth:
        config = tf.compat.v1.ConfigProto()
        config.gpu_options.allow_growth = True
        sess = tf.compat.v1.Session(config=config)
    else:
        sess = tf.compat.v1.Session()
```

calls upon v1 specific features.

I guess I mean, if you would take PRs to remove all calls to `tf.compat.v1` that might be something we can help.

**Comment by MMathisLab** [comment]
absolutely!

**Pull request closed without merging**
