### PR TITLE
Improvements to the model zoo's GUI tab

### PR DESCRIPTION
**Pull request by jeylau**
- Move the execution of the video adaptation code to a separate thread
- Add infinite progress bar in the GUI status bar
- Add extra widgets to grant users more control

Screenshot 2023-10-31 at 6 44 44 PM

### CODE REVIEW

**Comment by AlexEMG** [comment]
Looks great, @yeshaokai what do you think?

**Comment by yeshaokai** [comment]
Discussed with Jessy and it looks good to me

**Comment by MMathisLab** [comment]
Is there a help button? Any guidance to help the user to know what "threshold" is? Why they should or should not use adaptation? 

What form should scale be? This should be smartly set and not exposed - it's also irrelevant for quadruped model with top down...

**Review by MMathisLab — CHANGES_REQUESTED** [review]
The users need more guidance. We really need to bring back the help button!

Scale list should be hidden or a long paragraph on what size our model is trained on, and dynamically updated based on the selection of a model.

**Comment by jeylau** [comment]
I don't think we can hide scale list, as it requires user's input (as it's dependent on video/animal size, but not model type); if left unspecified, it internally defaults to video height +/- 50). If specified by the user though, note that we explicitly indicate that these should be a comma-separated list of integers, and we have an additional input validator that colors the input field frame (red, yellow, green) whether the input format is wrong, incomplete, or valid.

**Comment by MMathisLab** [comment]
Sure, but without docs it's not intuitive what it even is - so sure integers is clear, but we can do this smarter. Measure the video pixel size, scale it to our mean superanimal training dataset size... drop the box 💪

**Comment by jeylau** [comment]
- tooltip display on hovering over the question mark icon
Screenshot 2023-11-03 at 4 42 30 PM

- scrollable help dialog
Screenshot 2023-11-03 at 4 42 46 PM

**Review by AlexEMG — APPROVED** [review]

**Comment by n-poulsen** [comment]
The code looks good to me, but I get an issue when running with video adaptation (200 iterations):

```bash
/miniconda/envs/upa/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/miniconda/envs/upa/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/miniconda/envs/upa/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepLabCut/deeplabcut/pose_estimation_tensorflow/core/train.py", line 84, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/DeepLabCut/deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py", line 538, in next_batch
    temp.append(array[mask[inds]])
IndexError: invalid index to scalar variable.
```

I tested with the current code on `main` and do not get this issue. Does this happen to anyone else?

**Comment by jeylau** [comment]
@n-poulsen, I'm looking at it.

**Comment by jeylau** [comment]
This PR one is ready to merge; I pushed a fix in a separate branch as it's unrelated to the GUI.

**Pull request merged**
