### PR TITLE
Use cv2 named constants instead of opaque numbers to get properties

### PR DESCRIPTION
**Pull request by hmaarrfk**
These are some pretty minor cleanups.

I think since your project started a few of these constants might have gotten exported.

I developed this as I was developing a patch to re-use a preallocated array to interact with opencv, but I'm not sure of the utility of the larger patch.

This should aid in the readability of the code (it did for me).

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This is the remainder of the patch, let me know if you want me to include it:

In summary, it uses a preallocated array to avoid continued calls to `malloc` (which can be quite slow and cause fragmentation). Instead, a single video uses a single temporary buffer to continue to convert from the input color space to the final output color space.

<details><summary>OpenCV and pre-allocated arrays </summary>

```patch
diff --git a/deeplabcut/pose_estimation_tensorflow/predict_videos.py b/deeplabcut/pose_estimation_tensorflow/predict_videos.py
index 929027f..3531a1c 100644
--- a/deeplabcut/pose_estimation_tensorflow/predict_videos.py
+++ b/deeplabcut/pose_estimation_tensorflow/predict_videos.py
@@ -45,6 +45,19 @@ from deeplabcut.pose_estimation_tensorflow.core.openvino.session import (
 # Loading data, and defining model folder
 ####################################################
 
+def cv_dtype_to_numpy_dtype(cv_dtype):
+    cv_dtype = int(cv_dtype)
+    # https://github.com/opencv/opencv/blob/d861c03366a0883b2a84ff4a2de06e523891373d/modules/videoio/src/cap_v4l.cpp#L1638
+
+    return {
+        cv2.CV_8U: np.uint8,
+        cv2.CV_8S: np.int8,
+        cv2.CV_16U: np.uint16,
+        cv2.CV_16S: np.int16,
+        cv2.CV_32S: np.int32,
+        cv2.CV_32F: np.float32,
+        cv2.CV_64F: np.float64,
+    }[cv_dtype]
 
 def create_tracking_dataset(
     config,
@@ -793,12 +806,16 @@ def GetPoseF_GTF(cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize):
     batch_ind = 0  # keeps track of which image within a batch should be written to
     batch_num = 0  # keeps track of which batch you are at
     ny, nx = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)), int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
+    video_ny, video_nx = ny, nx
     if cfg["cropping"]:
         ny, nx = checkcropping(cfg, cap)
 
     pose_tensor = predict.extract_GPUprediction(
         outputs, dlc_cfg
     )  # extract_output_tensor(outputs, dlc_cfg)
+    frame_dtype = cv_dtype_to_numpy_dtype(cap.get(cv2.CAP_PROP_FORMAT))
+    frame_bgr = np.empty((video_ny, video_nx, 3), dtype=frame_dtype)
+    frame_rgb = np.empty((ny, nx, 3), dtype=frame_dtype)
     frames = np.empty(
         (batchsize, ny, nx, 3), dtype="ubyte"
     )  # this keeps all frames in a batch
@@ -809,15 +826,20 @@ def GetPoseF_GTF(cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize):
     while cap.isOpened():
         if counter != 0 and counter % step == 0:
             pbar.update(step)
-        ret, frame = cap.read()
+        ret, _ = cap.read(frame_bgr)
         if ret:
-            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
             if cfg["cropping"]:
-                frames[batch_ind] = img_as_ubyte(
-                    frame[cfg["y1"] : cfg["y2"], cfg["x1"] : cfg["x2"]]
-                )
+                # If we need cropping, get a view of the bgr frame
+                frame_cropped_bgr = frame_bgr[cfg["y1"]: cfg["y2"], cfg["x1"]: cfg["x2"], :]
             else:
-                frames[batch_ind] = img_as_ubyte(frame)
+                # Otherwise, just point to the original bgr frame
+                frame_cropped_bgr = frame_bgr
+
+            if frame_cropped_bgr.dtype != np.uint8:
+                cv2.cvtColor(frame_cropped_bgr, cv2.COLOR_BGR2RGB, dst=frame_rgb)
+                frames[batch_ind] = img_as_ubyte(frame_rgb)
+            else:
+                cv2.cvtColor(frame_cropped_bgr, cv2.COLOR_BGR2RGB, dst=frames[batch_ind])
             inds.append(counter)
             if batch_ind == batchsize - 1:
                 # pose = predict.getposeNP(frames,dlc_cfg, sess, inputs, outputs)
```
</details>

**Comment by jeylau** [comment]
Hey @hmaarrfk, it does improve readability a lot. Thanks! As for the rest of the patch, how do you handle videos too large to fit in memory?

**Comment by hmaarrfk** [comment]
The preallocated arrays I suggest in the patch only allocate memory for a constant multiple of a single frame.

Specifically, one array is allocated for `frame_bgr = ...` in BGR ordering for opencv. and the other is allocated in `frame_rgb = ...` .

Generally speaking, allocatting can be slow, for things roughly `~ 1 MB`. But the benefits may be hard to measure here with software decoding for x264.

I can followup with a different PR for "speedups" if you want to keep this one solely for readability.

**Review by jeylau — APPROVED** [review]

**Comment by jeylau** [comment]
Got it! Let's keep this PR for readability, and if you want to submit another PR, I'd be happy to review it. Thanks again! 😃

**Comment by hmaarrfk** [comment]
Great will do!

**Review by MMathisLab — APPROVED** [review]
- passive review; did not test but code looks good!

**Comment by hmaarrfk** [comment]
Thanks! I presume the automated tests are enough for this change. Isn't that correct?
image

**Pull request merged**
