### PR TITLE
New PyTorch DeepLabCut SuperAnimal demo notebook

### PR DESCRIPTION
**Pull request by yeshaokai**
Educational notebook for pytorch superanimal

### CODE REVIEW

**Comment by MMathisLab** [comment]
superanimal_analyze_images(superanimal_name,
                           model_name,
                           image_name,
                           max_individuals, 
                           out_folder = '/content/')

error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by MMathisLab** [comment]
There is an error with image inference, otherwise, I changed the text and simplified the video upload -- no need to connect to Google Drive for demo for image/video. 

I did not review training parts @n-poulsen can you do that first thing tomorrow?

**Comment by MMathisLab** [comment]
shall we merge @n-poulsen

**Comment by yeshaokai** [comment]
Looks good to me to merge @n-poulsen

**Review by n-poulsen — APPROVED** [review]

**Pull request merged**
