### PR TITLE
Compute distance statistics during evaluation

### PR DESCRIPTION
**Pull request by jeylau**
Provide detailed output of prediction error during evaluation (also written to .CSVs) and later reuse for more informed thresholds during cross-validation.

### CODE REVIEW

**Comment by jeylau** [comment]
@AlexEMG, I think this is finally ready for review 😄!

**Review by AlexEMG — CHANGES_REQUESTED** [review]
Looks good; ran test. Multianimal test fails:

  File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type
KeyError: 'distnorm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testscript_multianimal.py", line 109, in <module>
    config_path, n_iter=8, init_points=3
  File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/evaluate_multianimal.py", line 581, in evaluate_multianimal_crossvalidate
    inferencecfg.distnormalization = stats.pop('distnorm')
  File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/generic.py", line 790, in pop
    result = self[item]
  File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type
KeyError: 'distnorm'

**Comment by jeylau** [comment]
Good catch; I've just fixed it!

> Looks good; ran test. Multianimal test fails:
> 
> File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
> return self._engine.get_loc(key)
> File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type
> KeyError: 'distnorm'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "testscript_multianimal.py", line 109, in 
> config_path, n_iter=8, init_points=3
> File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/evaluate_multianimal.py", line 581, in evaluate_multianimal_crossvalidate
> inferencecfg.distnormalization = stats.pop('distnorm')
> File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/generic.py", line 790, in pop
> result = self[item]
> File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in **getitem**
> indexer = self.columns.get_loc(key)
> File "/home/alex/anaconda3/envs/DLC2/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
> return self._engine.get_loc(self._maybe_cast_indexer(key))
> File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type
> KeyError: 'distnorm'

**Review by AlexEMG — APPROVED** [review]

**Review by AlexEMG — APPROVED** [review]
Alors.

**Pull request merged**
