### PR TITLE
Creation of Johansson-like, keypoint-only videos

### PR DESCRIPTION
**Pull request by jeylau**
Very fast video creation triggered by `keypoints_only=True` in `create_label_videos()`.
The option to draw the skeleton remains valid.

### CODE REVIEW

**Comment by MMathisLab** [comment]
Tested on colab modelzoo:

!pip install git+https://github.com/DeepLabCut/DeepLabCut.git@johansson

with horsesideview: 

nice :) love it!

ezgif com-video-to-gif (3)

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
if we want to be really extra, the background could be black (or transparent) to really match the Johansson style ;)

**Comment by jeylau** [comment]
> if we want to be really extra, the background could be black (or transparent) to really match the Johansson style ;)

The option is there now: the default is black, but any color can be passed (using the function that is not wrapped in create_labeled_video) 😄

**Comment by MMathisLab** [comment]
nice :)
ezgif com-video-to-gif (4)

**Review by AlexEMG — APPROVED** [review]
Allez!

**Pull request merged**
