### PR TITLE
Save individual maps rather than a grid of them

### PR DESCRIPTION
**Pull request by jeylau**

### CODE REVIEW

**Comment by MMathisLab** [comment]
I think this is worth finishing, i.e. so each image can get a map, vs. subplots :)

**Comment by jeylau** [comment]
@MMathisLab, let me know if the output looks better to you 😃!

**Comment by MMathisLab** [comment]
looks very nice! The `scoremaps` and `LocRef` looks good; `PAFs`
 seem to be all separate images; maybe same image but different colors vs. 50 images if 50 PAFs? i.e. only 1 is shown as in this screencap

Screen Shot 2020-07-15 at 7 25 04 PM

**Comment by jeylau** [comment]
I tried plotting all graphs on the same image, but they overlap each other (which makes it unreadable even with different colors). I could add a keyword to let the user select either that behavior or the frame-by-frame fields, if that sounds good. Anyway, don't you think this function makes sense for only a subset of bodyparts?

**Review by AlexEMG — APPROVED** [review]
Perfectamente!

**Pull request merged**
